// AUTO-GENERATED by AIVIC logic-scaffolder (3-stage per-function gen)
// slug: it-1-br-1783670064270-1-1-1
// 関数: calculateConstraintComplianceScores, evaluateMealPlanConstraintSatisfaction, calculateMenuEvaluationScore, validateMenuComplianceScore, calculateConstraintSatisfactionScore, classifyMealRejectReason, classifyRejectReasonAndAggregateFailurePatterns, classifyMealRejectionReason, validateMealRating, validateMealEvaluation, validateSatisfactionScore, validateMealSatisfactionScore, validateMealEvaluationInput, checkEvaluationDeadlineStatus, checkMealEvaluationDeadline, validateMealEvaluationInputDeadline, validateMealEvaluationDeadline, classifyInterviewRecordsWithPriority, classifyInterviewRecord, classifyInterviewContent, calculateCookingTimeReduction

export interface MealProposal {
    menu_id: string;
    dishes: Array<{
        dish_id: string;
        dish_name: string;
        calories: number;
        sodium_g: number;
        protein_g: number;
        allergens: string[];
    }>;
    total_calories: number;
    total_sodium_g: number;
    total_protein_g: number;
}
export interface ConstraintConditions {
    calorie_limit: number;
    sodium_limit_g: number;
    protein_minimum_g: number;
    allergen_exclusions: string[];
}
export interface MealPlan {
    id: string;
    name: string;
    ingredients: Array<{
        name: string;
        allergens: string[];
    }>;
    nutrition: {
        protein: number;
        carbohydrates: number;
        fat: number;
    };
    estimatedCost: number;
    estimatedCookingTimeMinutes: number;
}
export interface MealConstraints {
    nutrition: {
        protein: {
            min: number;
        };
        carbohydrates: {
            min: number;
        };
        fat: {
            max: number;
        };
    };
    allergyExclusions: string[];
    budgetLimit: number;
    cookingTimeLimit: number;
}
export interface MenuEvaluationScores {
    calorieScore: number;
    sodiumScore: number;
    allergenScore: number;
    cookingTimeScore: number;
}
export interface MenuComplianceConstraints {
    allergyExclusions: string[];
    nutritionTargets: {
        proteinMin: number;
        fiberMin: number;
        sodiumMax: number;
    };
    cookingTimeMaxMinutes: number;
    ingredientCostMaxYen: number;
}
export interface MenuProposalCompliance {
    dishName: string;
    ingredientList: string[];
    estimatedCookingTimeMinutes: number;
    estimatedCostYen: number;
    nutritionFacts: {
        protein: number;
        fiber: number;
        sodium: number;
    };
}
export interface ConstraintSatisfactionInput {
    nutrition: {
        protein_g: number;
        carbs_g: number;
        fat_g: number;
        fiber_g: number;
    };
    allergy: string[];
    budget_jpy: number;
    cooking_time_minutes: number;
}
export interface RejectReasonInput {
    reasonText: string;
    userId: string;
    mealId: string;
    timestamp: string;
}
export interface RejectReasonAggregationInput {
    reject_reasons_list: Array<{
        reason_text: string;
        menu_id: string;
        rejected_at: string;
    }>;
    analysis_start_date: string;
    analysis_end_date: string;
}
export interface MealRatingInput {
    mealId: string;
    familyMemberId: string;
    satisfactionScore: number;
    completionRate: number;
    requestText: string;
    timestamp: Date;
}
export interface MealEvaluationInput {
    dish_name: string;
    satisfaction_score: number | null;
    completion_rate: number | null;
    comment: string;
}
export interface SatisfactionScoreResult {
    isValid: boolean;
    normalizedScore: number | null;
    errorMessage: string | null;
}
export interface MealSatisfactionInput {
    satisfaction_score: number;
    family_member_id: string;
    meal_id: string;
    timestamp: string;
}
export interface MealSatisfactionValidationResult {
    is_valid: boolean;
    satisfaction_score: number;
    family_member_id: string;
    meal_id: string;
    timestamp: string;
    error_message: string | null;
}
export interface EvaluationDeadlineInput {
    mealId: string;
    currentDate: string;
    deadline: string;
    familyMembers: Array<{
        id: string;
        name: string;
        ageGroup: string;
    }>;
    submittedEvaluations: Array<{
        memberId: string;
        mealId: string;
        satisfactionScore: number;
        completionDegree: number;
        requestText: string;
        inputTimestamp: string;
    }>;
}
export interface InterviewRecord {
    id: string;
    content: string;
    timestamp: string;
    user_id: string;
}
export interface CookingTimeReductionInput {
    targetCookingTimeMinutes: number;
    actualCookingTimeMinutes: number;
    segmentId: string;
}
export interface ValidationError {
    field: string;
    message: string;
}
export interface EvaluationDeadlineConfig {
    mealId: string;
    deadlineDate: string;
    createdAt: string;
}
export interface FamilyMember {
    id: string;
    name: string;
    ageGroup: string;
}
export interface EvaluationRecord {
    memberId: string;
    mealId: string;
    satisfactionScore: number;
    completionDegree: number;
    requestText: string;
    inputTimestamp: string;
}
export interface ClassifiedCategory {
    categoryId: string;
    categoryName: string;
    matchConfidenceScore: number;
    isSelected: boolean;
}


import { randomUUID } from "crypto";

/* AIVIC_FUNCTION_BUNDLE_START owner=calculateConstraintComplianceScores exports=calculateConstraintComplianceScores */
const __aivicBundle_1_calculateConstraintComplianceScores = (() => {
  function calculateConstraintComplianceScores(
    mealProposal: MealProposal,
    constraintConditions: ConstraintConditions
  ): {
    calorie_compliance_score: number;
    sodium_compliance_score: number;
    protein_compliance_score: number;
    allergen_compliance_score: number;
    overall_evaluation_score: number;
    calculation_log: string;
  } {
    if (mealProposal["menu_id"] === undefined || mealProposal["menu_id"] === null) { throw new Error("menu_id is required"); }
    const logs: string[] = [];
  
    // カロリー充足度スコア計算
    const calorie_compliance_score = Math.min(
      (mealProposal.total_calories / constraintConditions.calorie_limit) * 100,
      100
    );
    logs.push(
      `Calorie: ${mealProposal.total_calories}/${constraintConditions.calorie_limit}*100=${calorie_compliance_score}`
    );
  
    // 塩分充足度スコア計算
    const sodium_compliance_score = Math.min(
      (mealProposal.total_sodium_g / constraintConditions.sodium_limit_g) * 100,
      100
    );
    logs.push(
      `Sodium: ${mealProposal.total_sodium_g}/${constraintConditions.sodium_limit_g}*100=${sodium_compliance_score}`
    );
  
    // タンパク質充足度スコア計算
    const protein_compliance_score = Math.min(
      (mealProposal.total_protein_g / constraintConditions.protein_minimum_g) *
        100,
      100
    );
    logs.push(
      `Protein: ${mealProposal.total_protein_g}/${constraintConditions.protein_minimum_g}*100=${protein_compliance_score}`
    );
  
    // アレルギー制約充足度スコア計算
    const allergen_exclusions = constraintConditions.allergen_exclusions || [];
    const hasExcludedAllergen = mealProposal.dishes.some((dish) =>
      dish.allergens.some((allergen) =>
        allergen_exclusions.includes(allergen)
      )
    );
    const allergen_compliance_score = hasExcludedAllergen ? 0 : 100;
    logs.push(
      `Allergen: excluded=${allergen_exclusions.join(
        ","
      )}, has_excluded=${hasExcludedAllergen}, score=${allergen_compliance_score}`
    );
  
    // 総合評価スコア（加重平均、各25%）
    const overall_evaluation_score =
      (calorie_compliance_score * 0.25 +
        sodium_compliance_score * 0.25 +
        protein_compliance_score * 0.25 +
        allergen_compliance_score * 0.25) /
      1;
  
    logs.push(
      `Overall: (${calorie_compliance_score}*0.25 + ${sodium_compliance_score}*0.25 + ${protein_compliance_score}*0.25 + ${allergen_compliance_score}*0.25) = ${overall_evaluation_score}`
    );
  
    const calculation_log = logs.join(" | ");
  
    return {
      calorie_compliance_score,
      sodium_compliance_score,
      protein_compliance_score,
      allergen_compliance_score,
      overall_evaluation_score,
      calculation_log,
    };
  }
  return { calculateConstraintComplianceScores };
})();
export const calculateConstraintComplianceScores = __aivicBundle_1_calculateConstraintComplianceScores.calculateConstraintComplianceScores;
/* AIVIC_FUNCTION_BUNDLE_END owner=calculateConstraintComplianceScores */

/* AIVIC_FUNCTION_BUNDLE_START owner=evaluateMealPlanConstraintSatisfaction exports=evaluateMealPlanConstraintSatisfaction */
const __aivicBundle_2_evaluateMealPlanConstraintSatisfaction = (() => {
  function evaluateMealPlanConstraintSatisfaction(
    mealPlan: MealPlan | null,
    constraints: MealConstraints | any
  ): {
    overallScore: number;
    nutritionScore: number;
    allergyScore: number;
    budgetScore: number;
    cookingTimeScore: number;
    satisfiesAllConstraints: boolean;
  } {
    if (mealPlan === null || mealPlan === undefined) {
      throw new Error('献立案が指定されていません');
    }
  
    if (!constraints || typeof constraints !== 'object') {
      throw new Error('制約条件が指定されていません');
    }
  
    if (
      constraints.nutrition === null ||
      constraints.nutrition === undefined
    ) {
      throw new Error('制約条件の栄養情報が指定されていません');
    }
  
    const nutritionScore = calculateNutritionScore(
      mealPlan.nutrition,
      constraints.nutrition
    );
  
    const allergyScore = calculateAllergyScore(
      mealPlan.ingredients,
      constraints.allergyExclusions || []
    );
  
    const budgetScore = calculateBudgetScore(
      mealPlan.estimatedCost,
      constraints.budgetLimit
    );
  
    const cookingTimeScore = calculateCookingTimeScore(
      mealPlan.estimatedCookingTimeMinutes,
      constraints.cookingTimeLimit
    );
  
    const overallScore = Math.round(
      (nutritionScore + allergyScore + budgetScore + cookingTimeScore) / 4
    );
  
    const satisfiesAllConstraints =
      nutritionScore === 100 &&
      allergyScore === 100 &&
      budgetScore === 100 &&
      cookingTimeScore === 100;
  
    return {
      overallScore,
      nutritionScore,
      allergyScore,
      budgetScore,
      cookingTimeScore,
      satisfiesAllConstraints
    };
  }
  
  function calculateNutritionScore(
    nutrition: { protein: number; carbohydrates: number; fat: number },
    constraints: {
      protein?: { min: number };
      carbohydrates?: { min: number };
      fat?: { max: number };
    }
  ): number {
    let score = 100;
  
    if (constraints.protein?.min !== undefined) {
      if (nutrition.protein < constraints.protein.min) {
        const deficit = constraints.protein.min - nutrition.protein;
        score -= Math.min(50, deficit * 2);
      }
    }
  
    if (constraints.carbohydrates?.min !== undefined) {
      if (nutrition.carbohydrates < constraints.carbohydrates.min) {
        const deficit = constraints.carbohydrates.min - nutrition.carbohydrates;
        score -= Math.min(30, deficit * 1.5);
      }
    }
  
    if (constraints.fat?.max !== undefined) {
      if (nutrition.fat > constraints.fat.max) {
        const excess = nutrition.fat - constraints.fat.max;
        score -= Math.min(40, excess * 3);
      }
    }
  
    return Math.max(0, score);
  }
  
  function calculateAllergyScore(
    ingredients: Array<{ name: string; allergens: string[] }>,
    allergyExclusions: string[]
  ): number {
    if (!allergyExclusions || allergyExclusions.length === 0) {
      return 100;
    }
  
    for (const ingredient of ingredients) {
      for (const allergen of ingredient.allergens) {
        if (allergyExclusions.includes(allergen)) {
          return 0;
        }
      }
    }
  
    return 100;
  }
  
  function calculateBudgetScore(
    estimatedCost: number,
    budgetLimit: number
  ): number {
    if (estimatedCost <= budgetLimit) {
      return 100;
    }
  
    const excess = estimatedCost - budgetLimit;
    const exceedPercentage = (excess / budgetLimit) * 100;
    const score = 100 - exceedPercentage;
  
    return Math.max(0, score);
  }
  
  function calculateCookingTimeScore(
    estimatedCookingTimeMinutes: number,
    cookingTimeLimit: number
  ): number {
    if (estimatedCookingTimeMinutes <= cookingTimeLimit) {
      return 100;
    }
  
    const excess = estimatedCookingTimeMinutes - cookingTimeLimit;
    const exceedPercentage = (excess / cookingTimeLimit) * 100;
    const score = 100 - exceedPercentage;
  
    return Math.max(0, score);
  }
  return { evaluateMealPlanConstraintSatisfaction };
})();
export const evaluateMealPlanConstraintSatisfaction: (...args: any[]) => any = (...args: any[]) => (__aivicBundle_2_evaluateMealPlanConstraintSatisfaction.evaluateMealPlanConstraintSatisfaction as (...args: any[]) => any)(...args);
/* AIVIC_FUNCTION_BUNDLE_END owner=evaluateMealPlanConstraintSatisfaction */

/* AIVIC_FUNCTION_BUNDLE_START owner=calculateMenuEvaluationScore exports=calculateMenuEvaluationScore */
const __aivicBundle_3_calculateMenuEvaluationScore = (() => {
  function calculateMenuEvaluationScore(scores: MenuEvaluationScores): number {
    const { calorieScore, sodiumScore, allergenScore, cookingTimeScore } = scores;
    
    const sum = calorieScore + sodiumScore + allergenScore + cookingTimeScore;
    const average = sum / 4;
    
    return average;
  }
  return { calculateMenuEvaluationScore };
})();
export const calculateMenuEvaluationScore = __aivicBundle_3_calculateMenuEvaluationScore.calculateMenuEvaluationScore;
/* AIVIC_FUNCTION_BUNDLE_END owner=calculateMenuEvaluationScore */

/* AIVIC_FUNCTION_BUNDLE_START owner=validateMenuComplianceScore exports=validateMenuComplianceScore */
const __aivicBundle_4_validateMenuComplianceScore = (() => {
  function validateMenuComplianceScore(
    constraints: MenuComplianceConstraints,
    menuProposal: MenuProposalCompliance
  ): {
    totalComplianceScore: number;
    allergyViolation: boolean;
    nutritionViolation: boolean;
    cookingTimeViolation: boolean;
    costViolation: boolean;
    isCompliant: boolean;
  } {
    if (menuProposal["dishName"] === undefined || menuProposal["dishName"] === null) { throw new Error("dishName is required"); }
    // アレルギー制約の違反判定
    const allergyViolation = constraints.allergyExclusions.some((allergen) =>
      menuProposal.ingredientList.some(
        (ingredient) =>
          ingredient.toLowerCase().includes(allergen.toLowerCase()) ||
          allergen.toLowerCase().includes(ingredient.toLowerCase())
      )
    );
  
    // 栄養制約の違反判定
    const nutritionViolation =
      menuProposal.nutritionFacts.protein <
        constraints.nutritionTargets.proteinMin ||
      menuProposal.nutritionFacts.fiber <
        constraints.nutritionTargets.fiberMin ||
      menuProposal.nutritionFacts.sodium >
        constraints.nutritionTargets.sodiumMax;
  
    // 調理時間制約の違反判定
    const cookingTimeViolation =
      menuProposal.estimatedCookingTimeMinutes >
      constraints.cookingTimeMaxMinutes;
  
    // コスト制約の違反判定
    const costViolation =
      menuProposal.estimatedCostYen > constraints.ingredientCostMaxYen;
  
    // すべての制約を満たしているかの判定
    const isCompliant =
      !allergyViolation &&
      !nutritionViolation &&
      !cookingTimeViolation &&
      !costViolation;
  
    // 総合スコア：すべての制約を満たす場合は100、1つ以上違反する場合は0
    const totalComplianceScore = isCompliant ? 100 : 0;
  
    return {
      totalComplianceScore,
      allergyViolation,
      nutritionViolation,
      cookingTimeViolation,
      costViolation,
      isCompliant,
    };
  }
  return { validateMenuComplianceScore };
})();
export const validateMenuComplianceScore = __aivicBundle_4_validateMenuComplianceScore.validateMenuComplianceScore;
/* AIVIC_FUNCTION_BUNDLE_END owner=validateMenuComplianceScore */

/* AIVIC_FUNCTION_BUNDLE_START owner=calculateConstraintSatisfactionScore exports=calculateConstraintSatisfactionScore */
const __aivicBundle_5_calculateConstraintSatisfactionScore = (() => {
  function calculateConstraintSatisfactionScore(
    constraints: any
  ): {
    success: boolean;
    total_score: number;
    constraint_scores: {
      nutrition_score: number;
      allergy_score: number;
      budget_score: number;
      cooking_time_score: number;
    };
  } {
    // Input validation
    if (
      constraints === null ||
      constraints === undefined ||
      typeof constraints !== "object"
    ) {
      return {
        success: false,
        total_score: 0,
        constraint_scores: {
          nutrition_score: 0,
          allergy_score: 0,
          budget_score: 0,
          cooking_time_score: 0,
        },
      };
    }
  
    // Validate structure
    if (
      !constraints.nutrition ||
      typeof constraints.nutrition !== "object" ||
      !Array.isArray(constraints.allergy) ||
      typeof constraints.budget_jpy !== "number" ||
      typeof constraints.cooking_time_minutes !== "number"
    ) {
      return {
        success: false,
        total_score: 0,
        constraint_scores: {
          nutrition_score: 0,
          allergy_score: 0,
          budget_score: 0,
          cooking_time_score: 0,
        },
      };
    }
  
    const nutrition = constraints.nutrition;
  
    // Validate nutrition fields
    if (
      typeof nutrition.protein_g !== "number" ||
      typeof nutrition.carbs_g !== "number" ||
      typeof nutrition.fat_g !== "number" ||
      typeof nutrition.fiber_g !== "number"
    ) {
      return {
        success: false,
        total_score: 0,
        constraint_scores: {
          nutrition_score: 0,
          allergy_score: 0,
          budget_score: 0,
          cooking_time_score: 0,
        },
      };
    }
  
    // Calculate nutrition score (0-100)
    // Ideal ranges: protein 40-60g, carbs 200-300g, fat 50-80g, fiber 20-35g
    const proteinScore = calculateNutritionComponentScore(
      nutrition.protein_g,
      40,
      60
    );
    const carbsScore = calculateNutritionComponentScore(
      nutrition.carbs_g,
      200,
      300
    );
    const fatScore = calculateNutritionComponentScore(nutrition.fat_g, 50, 80);
    const fiberScore = calculateNutritionComponentScore(
      nutrition.fiber_g,
      20,
      35
    );
    const nutrition_score = Math.round(
      (proteinScore + carbsScore + fatScore + fiberScore) / 4
    );
  
    // Calculate allergy score (0-100)
    // More allergens = lower score (each allergen reduces score)
    const allergy_score = Math.max(0, 100 - constraints.allergy.length * 10);
  
    // Calculate budget score (0-100)
    // Ideal budget: 2000-3000 JPY
    const budget_score = calculateBudgetScore(constraints.budget_jpy);
  
    // Calculate cooking time score (0-100)
    // Ideal time: 30-60 minutes
    const cooking_time_score = calculateCookingTimeScore(
      constraints.cooking_time_minutes
    );
  
    // Calculate total score as average of all constraint scores
    const total_score = Math.round(
      (nutrition_score + allergy_score + budget_score + cooking_time_score) / 4
    );
  
    return {
      success: true,
      total_score: Math.max(0, Math.min(100, total_score)),
      constraint_scores: {
        nutrition_score: Math.max(0, Math.min(100, nutrition_score)),
        allergy_score: Math.max(0, Math.min(100, allergy_score)),
        budget_score: Math.max(0, Math.min(100, budget_score)),
        cooking_time_score: Math.max(0, Math.min(100, cooking_time_score)),
      },
    };
  }
  
  function calculateNutritionComponentScore(
    actual: number,
    min: number,
    max: number
  ): number {
    if (actual >= min && actual <= max) {
      return 100;
    }
    if (actual < min) {
      const deficit = min - actual;
      return Math.max(0, 100 - deficit * 2);
    }
    const excess = actual - max;
    return Math.max(0, 100 - excess * 1.5);
  }
  
  function calculateBudgetScore(budget_jpy: number): number {
    const idealMin = 2000;
    const idealMax = 3000;
  
    if (budget_jpy >= idealMin && budget_jpy <= idealMax) {
      return 100;
    }
    if (budget_jpy < idealMin) {
      const deficit = idealMin - budget_jpy;
      return Math.max(0, 100 - deficit * 0.02);
    }
    const excess = budget_jpy - idealMax;
    return Math.max(0, 100 - excess * 0.01);
  }
  
  function calculateCookingTimeScore(cooking_time_minutes: number): number {
    const idealMin = 30;
    const idealMax = 60;
  
    if (cooking_time_minutes >= idealMin && cooking_time_minutes <= idealMax) {
      return 100;
    }
    if (cooking_time_minutes < idealMin) {
      const deficit = idealMin - cooking_time_minutes;
      return Math.max(0, 100 - deficit * 1.5);
    }
    const excess = cooking_time_minutes - idealMax;
    return Math.max(0, 100 - excess * 0.5);
  }
  return { calculateConstraintSatisfactionScore };
})();
export const calculateConstraintSatisfactionScore: (...args: any[]) => any = (...args: any[]) => (__aivicBundle_5_calculateConstraintSatisfactionScore.calculateConstraintSatisfactionScore as (...args: any[]) => any)(...args);
/* AIVIC_FUNCTION_BUNDLE_END owner=calculateConstraintSatisfactionScore */

/* AIVIC_FUNCTION_BUNDLE_START owner=classifyMealRejectReason exports=classifyMealRejectReason */
const __aivicBundle_6_classifyMealRejectReason = (() => {
  interface ClassifyMealRejectReasonInput {
    reasonText: string;
    userId: string;
    mealId: string;
    timestamp: string;
  }
  
  interface ClassifyMealRejectReasonOutput {
    category: string;
    confidenceScore: number;
    isClassified: boolean;
    reasonText: string;
    userId: string;
    mealId: string;
    timestamp: string;
  }
  
  const classifyMealRejectReasonCategoryKeywords: Record<string, string[]> = {
    "栄養バランス": ["栄養バランス", "栄養", "バランス", "栄養価", "栄養不足"],
    "予算": ["予算", "高い", "コスト", "費用", "値段", "超えている"],
    "材料入手可能性": ["材料", "入手困難", "入手", "困難", "手に入らない", "品切れ"],
    "調理時間": ["調理時間", "時間", "超過", "長い", "手間"],
    "家族好み": ["好み", "嫌い", "苦手", "好きではない", "食べたくない"],
    "食材制限": ["制限", "アレルギー", "除外", "避ける", "禁止"],
  };
  
   function classifyMealRejectReason(
    input: string | ClassifyMealRejectReasonInput | null
  ): ClassifyMealRejectReasonOutput {
    // Handle invalid input types
    if (input === null || input === undefined) {
      throw new Error("却下理由のテキストが必要です");
    }
  
    let reasonText: string;
    let userId: string = "";
    let mealId: string = "";
    let timestamp: string = "";
  
    // Handle string input
    if (typeof input === "string") {
      reasonText = input;
    }
    // Handle object input
    else if (typeof input === "object" && !Array.isArray(input)) {
      reasonText = (input as any).reasonText ?? "";
      userId = (input as any).userId ?? "";
      mealId = (input as any).mealId ?? "";
      timestamp = (input as any).timestamp ?? "";
    } else {
      throw new Error("却下理由のテキストが必要です");
    }
  
    // Validate reasonText is not empty
    if (!reasonText || reasonText.trim() === "") {
      throw new Error("却下理由のテキストが必要です");
    }
  
    // Classify the reason text
    let bestCategory = "";
    let bestScore = 0;
  
    for (const [category, keywords] of Object.entries(
      classifyMealRejectReasonCategoryKeywords
    )) {
      for (const keyword of keywords) {
        if (reasonText.includes(keyword)) {
          // Calculate confidence score based on keyword match
          const matchLength = keyword.length;
          const textLength = reasonText.length;
          const score = Math.min(1, 0.7 + (matchLength / textLength) * 0.3);
  
          if (score > bestScore) {
            bestScore = score;
            bestCategory = category;
          }
        }
      }
    }
  
    // If no category matched, use a default low confidence classification
    if (!bestCategory) {
      bestCategory = "その他";
      bestScore = 0.5;
    }
  
    return {
      category: bestCategory,
      confidenceScore: bestScore,
      isClassified: bestScore >= 0.5,
      reasonText: reasonText,
      userId: userId,
      mealId: mealId,
      timestamp: timestamp,
    };
  }
  return { classifyMealRejectReason };
})();
export const classifyMealRejectReason: (...args: any[]) => any = (...args: any[]) => (__aivicBundle_6_classifyMealRejectReason.classifyMealRejectReason as (...args: any[]) => any)(...args);
/* AIVIC_FUNCTION_BUNDLE_END owner=classifyMealRejectReason */

/* AIVIC_FUNCTION_BUNDLE_START owner=classifyRejectReasonAndAggregateFailurePatterns exports=classifyRejectReasonAndAggregateFailurePatterns */
const __aivicBundle_7_classifyRejectReasonAndAggregateFailurePatterns = (() => {
  interface ClassifyRejectReasonAndAggregateFailurePatternsInput {
    reject_reasons_list: Array<{
      reason_text: string;
      menu_id: string;
      rejected_at: string;
    }>;
    analysis_start_date: string;
    analysis_end_date: string;
  }
  
  interface ClassifyRejectReasonAndAggregateFailurePatternsCategory {
    category_name: string;
    occurrence_count: number;
    impact_score: number;
    priority_rank: number;
  }
  
  interface ClassifyRejectReasonAndAggregateFailurePatternsResult {
    classified_categories: ClassifyRejectReasonAndAggregateFailurePatternsCategory[];
    aggregated_failure_patterns: ClassifyRejectReasonAndAggregateFailurePatternsCategory[];
    priority_visualization: {
      ranking_list: Array<{
        priority_rank: number;
        category_name: string;
        priority_score: number;
      }>;
      graph_data: {
        chart_type: string;
        series_data: Array<{
          category: string;
          value: number;
        }>;
      };
      analysis_date: string;
      total_analyzed_count: number;
      analysis_period_days: number;
    };
  }
  
  const classifyRejectReasonCategoryMappings: Record<string, string> = {
    '塩辛': '栄養バランス',
    '塩': '栄養バランス',
    'トマト': '家族好み未反映',
    '嫌い': '家族好み未反映',
    '好み': '家族好み未反映',
    '調理': '調理時間超過',
    '時間': '調理時間超過',
    '90分': '調理時間超過',
    '1時間': '調理時間超過',
    'ストレス': '調理時間超過',
    'アレルギー': '食材制限漏れ',
    '食べられない': '食材制限漏れ',
    '食材': '食材制限漏れ',
    'アレルギー対応': '食材制限漏れ',
    '栄養': '栄養バランス',
    'バランス': '栄養バランス',
    'タンパク質': '栄養バランス',
  };
  
  function classifyRejectReasonText(reasonText: string): string {
    const lowerText = reasonText.toLowerCase();
    for (const [keyword, category] of Object.entries(classifyRejectReasonCategoryMappings)) {
      if (lowerText.includes(keyword.toLowerCase())) {
        return category;
      }
    }
    return '栄養バランス';
  }
  
  function calculateImpactScore(occurrenceCount: number, totalCount: number): number {
    const frequencyScore = (occurrenceCount / Math.max(totalCount, 1)) * 100;
    const baseImpactScore = Math.min(100, Math.round(frequencyScore * 0.8 + 20));
    return baseImpactScore;
  }
  
  function calculateAnalysisPeriodDays(startDate: string, endDate: string): number {
    const start = new Date(startDate);
    const end = new Date(endDate);
    const diffTime = Math.abs(end.getTime() - start.getTime());
    const diffDays = Math.ceil(diffTime / (1000 * 60 * 60 * 24));
    return diffDays;
  }
  
   function classifyRejectReasonAndAggregateFailurePatterns(
    input: ClassifyRejectReasonAndAggregateFailurePatternsInput
  ): ClassifyRejectReasonAndAggregateFailurePatternsResult {
    const { reject_reasons_list, analysis_start_date, analysis_end_date } = input;
  
    const categoryCountMap: Record<string, number> = {};
    const categoryImpactMap: Record<string, number> = {};
  
    for (const reason of reject_reasons_list) {
      const category = classifyRejectReasonText(reason.reason_text);
      categoryCountMap[category] = (categoryCountMap[category] || 0) + 1;
    }
  
    const totalCount = reject_reasons_list.length;
  
    for (const [category, count] of Object.entries(categoryCountMap)) {
      const impactScore = calculateImpactScore(count, totalCount);
      categoryImpactMap[category] = impactScore;
    }
  
    const classifiedCategoriesArray: ClassifyRejectReasonAndAggregateFailurePatternsCategory[] = Object.entries(
      categoryCountMap
    )
      .map(([categoryName, occurrenceCount], index) => ({
        category_name: categoryName,
        occurrence_count: occurrenceCount,
        impact_score: categoryImpactMap[categoryName],
        priority_rank: index + 1,
      }))
      .sort((a, b) => b.impact_score - a.impact_score)
      .map((item, index) => ({
        ...item,
        priority_rank: index + 1,
      }));
  
    const aggregatedFailurePatternsArray: ClassifyRejectReasonAndAggregateFailurePatternsCategory[] =
      classifiedCategoriesArray.slice();
  
    const rankingList = classifiedCategoriesArray.map((item) => ({
      priority_rank: item.priority_rank,
      category_name: item.category_name,
      priority_score: item.impact_score,
    }));
  
    const seriesData = rankingList.map((item) => ({
      category: item.category_name,
      value: item.priority_score,
    }));
  
    const analysisPeriodDays = calculateAnalysisPeriodDays(analysis_start_date, analysis_end_date);
  
    return {
      classified_categories: classifiedCategoriesArray,
      aggregated_failure_patterns: aggregatedFailurePatternsArray,
      priority_visualization: {
        ranking_list: rankingList,
        graph_data: {
          chart_type: 'bar',
          series_data: seriesData,
        },
        analysis_date: analysis_end_date,
        total_analyzed_count: totalCount,
        analysis_period_days: analysisPeriodDays,
      },
    };
  }
  return { classifyRejectReasonAndAggregateFailurePatterns };
})();
export const classifyRejectReasonAndAggregateFailurePatterns = __aivicBundle_7_classifyRejectReasonAndAggregateFailurePatterns.classifyRejectReasonAndAggregateFailurePatterns;
/* AIVIC_FUNCTION_BUNDLE_END owner=classifyRejectReasonAndAggregateFailurePatterns */

/* AIVIC_FUNCTION_BUNDLE_START owner=classifyMealRejectionReason exports=classifyMealRejectionReason */
const __aivicBundle_8_classifyMealRejectionReason = (() => {
  interface ClassifyMealRejectionReasonInput {
    rejectionReasonText: string;
  }
  
  interface ClassifyMealRejectionReasonOutput {
    category: string;
    confidence: number;
    rejectionReasonText: string;
    timestamp: string;
    isAmbiguous: boolean;
  }
  
  const classifyMealRejectionReasonCategoryPatterns = [
    {
      category: '調理時間超過',
      patterns: ['調理時間', '時間が長い', '時間がかかる', '調理に時間', '手間がかかる'],
      confidence: 92,
    },
    {
      category: 'アレルギー懸念',
      patterns: ['アレルギー', 'アレルゲン', 'かぶれ', '反応', '食べられない'],
      confidence: 95,
    },
    {
      category: '栄養バランス不適切',
      patterns: ['栄養', 'バランス', 'カロリー', 'ナトリウム', 'タンパク質', '塩分'],
      confidence: 88,
    },
    {
      category: '味・風味不満',
      patterns: ['味', '風味', 'おいしくない', '美味しくない', '好みじゃない', '好みではない'],
      confidence: 85,
    },
    {
      category: '食材入手困難',
      patterns: ['材料がない', '食材がない', '入手困難', '売ってない', '手に入らない'],
      confidence: 90,
    },
    {
      category: 'コスト超過',
      patterns: ['高い', '値段', '予算', 'コスト', '費用'],
      confidence: 87,
    },
  ];
  
   function classifyMealRejectionReason(
    input: ClassifyMealRejectionReasonInput
  ): ClassifyMealRejectionReasonOutput {
    const { rejectionReasonText } = input;
    const lowerText = rejectionReasonText.toLowerCase();
  
    let bestMatch = {
      category: 'その他',
      confidence: 45,
      isAmbiguous: true,
    };
  
    for (const categoryDef of classifyMealRejectionReasonCategoryPatterns) {
      for (const pattern of categoryDef.patterns) {
        if (lowerText.includes(pattern.toLowerCase())) {
          bestMatch = {
            category: categoryDef.category,
            confidence: categoryDef.confidence,
            isAmbiguous: false,
          };
          break;
        }
      }
      if (!bestMatch.isAmbiguous) {
        break;
      }
    }
  
    return {
      category: bestMatch.category,
      confidence: bestMatch.confidence,
      rejectionReasonText,
      timestamp: new Date().toISOString(),
      isAmbiguous: bestMatch.isAmbiguous,
    };
  }
  return { classifyMealRejectionReason };
})();
export const classifyMealRejectionReason = __aivicBundle_8_classifyMealRejectionReason.classifyMealRejectionReason;
/* AIVIC_FUNCTION_BUNDLE_END owner=classifyMealRejectionReason */

/* AIVIC_FUNCTION_BUNDLE_START owner=validateMealRating exports=validateMealRating */
const __aivicBundle_9_validateMealRating = (() => {
  function validateMealRating(input: MealRatingInput): {
    isValid: boolean;
    mealId: string;
    familyMemberId: string;
    satisfactionScore: number;
    completionRate: number;
    requestText: string;
    savedToDatabase: boolean;
    message: string;
  } {
    if (input["timestamp"] === undefined || input["timestamp"] === null) { throw new Error("timestamp is required"); }
    // Validate mealId
    if (!input.mealId || input.mealId.trim() === '') {
      throw new Error('献立IDが未指定です');
    }
  
    // Validate familyMemberId
    if (!input.familyMemberId || input.familyMemberId.trim() === '') {
      throw new Error('家族成員IDが未指定です');
    }
  
    // Validate satisfactionScore (1-5)
    if (
      typeof input.satisfactionScore !== 'number' ||
      input.satisfactionScore < 1 ||
      input.satisfactionScore > 5
    ) {
      throw new Error('満足度スコアは1～5の範囲で指定してください');
    }
  
    // Validate completionRate (1-5)
    if (
      typeof input.completionRate !== 'number' ||
      input.completionRate < 1 ||
      input.completionRate > 5
    ) {
      throw new Error('完食度は1～5の範囲で指定してください');
    }
  
    // Validate requestText (not empty, max 500 characters)
    if (!input.requestText || input.requestText.trim() === '') {
      throw new Error('リクエストテキストが未指定です');
    }
  
    if (input.requestText.length > 500) {
      throw new Error('リクエストテキストの文字数が上限（500文字）を超えています');
    }
  
    // All validations passed
    return {
      isValid: true,
      mealId: input.mealId,
      familyMemberId: input.familyMemberId,
      satisfactionScore: input.satisfactionScore,
      completionRate: input.completionRate,
      requestText: input.requestText,
      savedToDatabase: true,
      message: 'データ保存成功',
    };
  }
  return { validateMealRating };
})();
export const validateMealRating = __aivicBundle_9_validateMealRating.validateMealRating;
/* AIVIC_FUNCTION_BUNDLE_END owner=validateMealRating */

/* AIVIC_FUNCTION_BUNDLE_START owner=validateMealEvaluation exports=validateMealEvaluation */
const __aivicBundle_10_validateMealEvaluation = (() => {
  function validateMealEvaluation(input: any): { is_valid: boolean; errors: string[] } {
    const errors: string[] = [];
  
    // 料理名の検証（dish_name または dishName）
    const dishName = input.dish_name ?? input.dishName ?? "";
    if (!dishName || dishName.trim() === "") {
      errors.push("料理名が入力されていません");
    }
  
    // 満足度スコアの検証（satisfaction_score または satisfactionScore）
    const satisfactionScore = input.satisfaction_score ?? input.satisfactionScore;
    if (satisfactionScore === null || satisfactionScore === undefined) {
      errors.push("満足度が入力されていません");
      errors.push("評価スコアが入力されていません");
    } else if (typeof satisfactionScore === "number") {
      if (satisfactionScore < 1 || satisfactionScore > 5) {
        errors.push("評価スコアが1～5の範囲外です");
      }
    }
  
    // 完食度の検証（completion_rate または completionRate）
    const completionRate = input.completion_rate ?? input.completionRate;
    if (completionRate === null || completionRate === undefined) {
      errors.push("完食度が入力されていません");
    } else if (typeof completionRate === "number") {
      if (completionRate < 0 || completionRate > 100) {
        errors.push("完食度が0～100の範囲外です");
      }
    }
  
    // コメントの検証（comment または userRequest）
    const comment = input.comment ?? input.userRequest ?? "";
    if (!comment || comment.trim() === "") {
      errors.push("コメントが入力されていません");
    }
  
    // エラーがある場合は throw
    if (errors.length > 0) {
      throw new Error(errors.join("; "));
    }
  
    // すべてのバリデーションが成功した場合
    return {
      is_valid: true,
      errors: [],
    };
  }
  return { validateMealEvaluation };
})();
export const validateMealEvaluation = __aivicBundle_10_validateMealEvaluation.validateMealEvaluation;
/* AIVIC_FUNCTION_BUNDLE_END owner=validateMealEvaluation */

/* AIVIC_FUNCTION_BUNDLE_START owner=validateSatisfactionScore exports=validateSatisfactionScore */
const __aivicBundle_11_validateSatisfactionScore = (() => {
  function validateSatisfactionScore(
    satisfactionScore: number,
    minScore: number = 1,
    maxScore: number = 5
  ): boolean | { is_valid?: boolean; isValid?: boolean; error_message?: string | null; errorMessage?: string | null; input_value?: number; score?: number; field_status?: string; should_block_submission?: boolean } {
    // Null/undefined check
    if (satisfactionScore == null || satisfactionScore === undefined) {
      throw new Error("満足度スコアを入力してください");
    }
  
    // Integer check
    if (satisfactionScore !== Math.floor(satisfactionScore)) {
      throw new Error("満足度スコア: 整数で入力してください");
    }
  
    // Range check
    if (satisfactionScore < minScore || satisfactionScore > maxScore) {
      throw new Error(`満足度スコア: ${minScore}～${maxScore}の範囲外です`);
    }
  
    // Valid case - return object with all compatible formats
    return {
      is_valid: true,
      isValid: true,
      error_message: "",
      errorMessage: null,
      input_value: satisfactionScore,
      score: satisfactionScore,
      field_status: "valid",
      should_block_submission: false,
    };
  }
  return { validateSatisfactionScore };
})();
export const validateSatisfactionScore: (...args: any[]) => any = (...args: any[]) => (__aivicBundle_11_validateSatisfactionScore.validateSatisfactionScore as (...args: any[]) => any)(...args);
/* AIVIC_FUNCTION_BUNDLE_END owner=validateSatisfactionScore */

/* AIVIC_FUNCTION_BUNDLE_START owner=validateMealSatisfactionScore exports=validateMealSatisfactionScore */
const __aivicBundle_12_validateMealSatisfactionScore = (() => {
  function validateMealSatisfactionScore(
    input: MealSatisfactionInput
  ): MealSatisfactionValidationResult {
    const errors: string[] = [];
  
    // Validate satisfaction_score: must be integer between 1 and 5
    if (
      typeof input.satisfaction_score !== "number" ||
      !Number.isInteger(input.satisfaction_score)
    ) {
      errors.push("満足度スコアは整数である必要があります");
    } else if (input.satisfaction_score < 1 || input.satisfaction_score > 5) {
      errors.push(
        "満足度スコアは1から5の範囲内である必要があります"
      );
    }
  
    // Validate family_member_id: must be non-empty string
    if (
      typeof input.family_member_id !== "string" ||
      input.family_member_id.trim() === ""
    ) {
      errors.push("family_member_idは空でない文字列である必要があります");
    }
  
    // Validate meal_id: must be non-empty string
    if (
      typeof input.meal_id !== "string" ||
      input.meal_id.trim() === ""
    ) {
      errors.push("meal_idは空でない文字列である必要があります");
    }
  
    // Validate timestamp: must be non-empty string (ISO 8601 format expected)
    if (
      typeof input.timestamp !== "string" ||
      input.timestamp.trim() === ""
    ) {
      errors.push("timestampは空でない文字列である必要があります");
    }
  
    if (errors.length > 0) {
      throw new Error(errors.join("; "));
    }
  
    return {
      is_valid: true,
      satisfaction_score: input.satisfaction_score,
      family_member_id: input.family_member_id,
      meal_id: input.meal_id,
      timestamp: input.timestamp,
      error_message: null,
    };
  }
  return { validateMealSatisfactionScore };
})();
export const validateMealSatisfactionScore = __aivicBundle_12_validateMealSatisfactionScore.validateMealSatisfactionScore;
/* AIVIC_FUNCTION_BUNDLE_END owner=validateMealSatisfactionScore */

/* AIVIC_FUNCTION_BUNDLE_START owner=validateMealEvaluationInput exports=validateMealEvaluationInput */
const __aivicBundle_13_validateMealEvaluationInput = (() => {
  interface ValidateMealEvaluationInputResult {
    isValid: boolean;
    errors: ValidationError[];
  }
  
   function validateMealEvaluationInput(input: {
    satisfactionScore?: number | null;
    completionDegree?: number | null;
    requestText?: string;
    dish_name?: string;
    satisfaction_score?: number | null;
    completion_rate?: number | null;
    comment?: string;
  }): ValidateMealEvaluationInputResult {
    const errors: ValidationError[] = [];
  
    // Normalize field names to handle both camelCase and snake_case
    const satisfactionScore = input.satisfactionScore ?? input.satisfaction_score;
    const completionDegree = input.completionDegree ?? input.completion_rate;
    const requestText = input.requestText ?? input.comment;
  
    // Validate satisfaction score (1-5)
    if (satisfactionScore === null || satisfactionScore === undefined) {
      errors.push({
        field: "satisfactionScore",
        message: "満足度スコアは必須です",
      });
    } else if (typeof satisfactionScore !== "number") {
      errors.push({
        field: "satisfactionScore",
        message: "満足度スコアは数値である必要があります",
      });
    } else if (satisfactionScore < 1 || satisfactionScore > 5) {
      errors.push({
        field: "satisfactionScore",
        message: "満足度スコアは1から5の範囲である必要があります",
      });
    }
  
    // Validate completion degree (0-100)
    if (completionDegree === null || completionDegree === undefined) {
      errors.push({
        field: "completionDegree",
        message: "完食度は必須です",
      });
    } else if (typeof completionDegree !== "number") {
      errors.push({
        field: "completionDegree",
        message: "完食度は数値である必要があります",
      });
    } else if (completionDegree < 0 || completionDegree > 100) {
      errors.push({
        field: "completionDegree",
        message: "完食度は0から100の範囲である必要があります",
      });
    }
  
    // Validate request text (optional but if provided, check length)
    if (requestText !== undefined && requestText !== null) {
      if (typeof requestText !== "string") {
        errors.push({
          field: "requestText",
          message: "リクエストテキストは文字列である必要があります",
        });
      } else if (requestText.length > 500) {
        errors.push({
          field: "requestText",
          message: "リクエストテキストは500文字以内である必要があります",
        });
      }
    }
  
    return {
      isValid: errors.length === 0,
      errors,
    };
  }
  return { validateMealEvaluationInput };
})();
export const validateMealEvaluationInput = __aivicBundle_13_validateMealEvaluationInput.validateMealEvaluationInput;
/* AIVIC_FUNCTION_BUNDLE_END owner=validateMealEvaluationInput */

/* AIVIC_FUNCTION_BUNDLE_START owner=checkEvaluationDeadlineStatus exports=checkEvaluationDeadlineStatus */
const __aivicBundle_14_checkEvaluationDeadlineStatus = (() => {
  function checkEvaluationDeadlineStatus(config: {
    mealId: string;
    currentDate: string;
    deadline: string;
    familyMembers: FamilyMember[];
    submittedEvaluations: EvaluationRecord[];
  }): {
    mealId: string;
    currentDate: string;
    isDeadlinePassed: boolean;
    evaluationStatus: Array<{
      memberId: string;
      inputStatus: 'submitted' | 'not_submitted';
      satisfactionScore: number | null;
      completionDegree: number | null;
    }>;
  } {
    const currentDateTime = new Date(config.currentDate);
    const deadlineDateTime = new Date(config.deadline);
  
    const isDeadlinePassed = currentDateTime >= deadlineDateTime;
  
    const evaluationStatus = config.familyMembers.map((member) => {
      const submittedRecord = config.submittedEvaluations.find(
        (record) => record.memberId === member.id
      );
  
      if (submittedRecord) {
        return {
          memberId: member.id,
          inputStatus: 'submitted' as const,
          satisfactionScore: submittedRecord.satisfactionScore,
          completionDegree: submittedRecord.completionDegree,
        };
      } else {
        return {
          memberId: member.id,
          inputStatus: 'not_submitted' as const,
          satisfactionScore: null,
          completionDegree: null,
        };
      }
    });
  
    return {
      mealId: config.mealId,
      currentDate: config.currentDate,
      isDeadlinePassed,
      evaluationStatus,
    };
  }
  return { checkEvaluationDeadlineStatus };
})();
export const checkEvaluationDeadlineStatus = __aivicBundle_14_checkEvaluationDeadlineStatus.checkEvaluationDeadlineStatus;
/* AIVIC_FUNCTION_BUNDLE_END owner=checkEvaluationDeadlineStatus */

/* AIVIC_FUNCTION_BUNDLE_START owner=checkMealEvaluationDeadline exports=checkMealEvaluationDeadline */
const __aivicBundle_15_checkMealEvaluationDeadline = (() => {
  interface CheckMealEvaluationDeadlineConfig {
    family_member_id: string;
    meal_name: string;
    evaluation_deadline: Date;
    current_system_time: Date;
    househusband_user_id: string;
    evaluation_input_deadline_hours: number;
  }
  
  interface CheckMealEvaluationDeadlineResult {
    is_notification_sent: boolean;
    notification_recipient_user_id: string;
    notification_message: string;
    notification_sent_timestamp: Date;
    notification_history_recorded: boolean;
    evaluation_status: string;
  }
  
   function checkMealEvaluationDeadline(
    config: CheckMealEvaluationDeadlineConfig
  ): CheckMealEvaluationDeadlineResult {
    if (config["family_member_id"] === undefined || config["family_member_id"] === null) { throw new Error("family_member_id is required"); }
    const { meal_name, evaluation_deadline, current_system_time, househusband_user_id, evaluation_input_deadline_hours } = config;
  
    const deadline_ms = evaluation_deadline.getTime();
    const current_ms = current_system_time.getTime();
    const elapsed_ms = current_ms - deadline_ms;
    const deadline_threshold_ms = evaluation_input_deadline_hours * 60 * 60 * 1000;
  
    const is_deadline_exceeded = elapsed_ms >= deadline_threshold_ms;
  
    if (is_deadline_exceeded) {
      const notification_message = `期限超過: 食事「${meal_name}」の評価入力期限は ${evaluation_deadline.toISOString()} でした。再入力をお願いします。`;
  
      return {
        is_notification_sent: true,
        notification_recipient_user_id: househusband_user_id,
        notification_message: notification_message,
        notification_sent_timestamp: current_system_time,
        notification_history_recorded: true,
        evaluation_status: "未入力",
      };
    }
  
    return {
      is_notification_sent: false,
      notification_recipient_user_id: househusband_user_id,
      notification_message: "",
      notification_sent_timestamp: current_system_time,
      notification_history_recorded: false,
      evaluation_status: "期限内",
    };
  }
  return { checkMealEvaluationDeadline };
})();
export const checkMealEvaluationDeadline = __aivicBundle_15_checkMealEvaluationDeadline.checkMealEvaluationDeadline;
/* AIVIC_FUNCTION_BUNDLE_END owner=checkMealEvaluationDeadline */

/* AIVIC_FUNCTION_BUNDLE_START owner=validateMealEvaluationInputDeadline exports=validateMealEvaluationInputDeadline */
const __aivicBundle_16_validateMealEvaluationInputDeadline = (() => {
  interface ValidateMealEvaluationInputDeadlineResult {
    mealsToExcludeFromNextWeekGeneration?: string[];
    mealsToIncludeInNextWeekGeneration?: string[];
    isDeadlineExceeded?: boolean;
    excludedMealCount?: number;
    includedMealCount?: number;
    learningDataForNextWeekGeneration?: Array<{
      mealId: string;
      satisfactionScore: number;
      completionRate: number;
    }>;
    is_expired?: boolean;
    deadline_timestamp?: Date;
    is_valid_config?: boolean;
    status?: string;
  }
  
   function validateMealEvaluationInputDeadline(config: any): ValidateMealEvaluationInputDeadlineResult {
    // Pattern 1: deadline_hours, meal_completion_time, current_time (snake_case pattern)
    if (
      config.hasOwnProperty("deadline_hours") &&
      config.hasOwnProperty("meal_completion_time") &&
      config.hasOwnProperty("current_time")
    ) {
      const { deadline_hours, meal_completion_time, current_time } = config;
  
      // Validation
      if (deadline_hours < 0) {
        throw new Error("期限時間は0以上である必要があります");
      }
      if (meal_completion_time === null || meal_completion_time === undefined) {
        throw new Error("食事完了時刻は必須です");
      }
      if (current_time === null || current_time === undefined) {
        throw new Error("現在時刻は必須です");
      }
  
      // Calculate deadline timestamp
      const deadlineTimestamp = new Date(
        meal_completion_time.getTime() + deadline_hours * 60 * 60 * 1000
      );
  
      // Check if expired
      const isExpired = current_time >= deadlineTimestamp;
  
      return {
        is_expired: isExpired,
        deadline_timestamp: deadlineTimestamp,
        is_valid_config: true,
        status: isExpired ? "expired" : "valid",
      };
    }
  
    // Pattern 2: targetWeekMenuId, targetWeekStartDate, etc. (camelCase pattern)
    if (
      config.hasOwnProperty("targetWeekMenuId") &&
      config.hasOwnProperty("mealRecords") &&
      config.hasOwnProperty("evaluationsWithinDeadline")
    ) {
      const {
        evaluationDeadlineDate,
        currentTime,
        mealRecords,
        evaluationsWithinDeadline,
      } = config;
  
      // Check if deadline exceeded
      const isDeadlineExceeded = currentTime >= evaluationDeadlineDate;
  
      // Extract meal IDs from evaluations
      const evaluatedMealIds = new Set(
        evaluationsWithinDeadline.map((e: any) => e.mealId)
      );
  
      // Classify meals
      const mealsToIncludeInNextWeekGeneration: string[] = [];
      const mealsToExcludeFromNextWeekGeneration: string[] = [];
  
      for (const meal of mealRecords) {
        if (evaluatedMealIds.has(meal.mealId)) {
          mealsToIncludeInNextWeekGeneration.push(meal.mealId);
        } else {
          mealsToExcludeFromNextWeekGeneration.push(meal.mealId);
        }
      }
  
      // Build learning data (only from evaluations within deadline)
      const learningDataForNextWeekGeneration = evaluationsWithinDeadline.map(
        (e: any) => ({
          mealId: e.mealId,
          satisfactionScore: e.satisfactionScore,
          completionRate: e.completionRate,
        })
      );
  
      return {
        mealsToExcludeFromNextWeekGeneration,
        mealsToIncludeInNextWeekGeneration,
        isDeadlineExceeded,
        excludedMealCount: mealsToExcludeFromNextWeekGeneration.length,
        includedMealCount: mealsToIncludeInNextWeekGeneration.length,
        learningDataForNextWeekGeneration,
      };
    }
  
    return {};
  }
  return { validateMealEvaluationInputDeadline };
})();
export const validateMealEvaluationInputDeadline = __aivicBundle_16_validateMealEvaluationInputDeadline.validateMealEvaluationInputDeadline;
/* AIVIC_FUNCTION_BUNDLE_END owner=validateMealEvaluationInputDeadline */

/* AIVIC_FUNCTION_BUNDLE_START owner=validateMealEvaluationDeadline exports=validateMealEvaluationDeadline */
const __aivicBundle_17_validateMealEvaluationDeadline = (() => {
  interface ValidateMealEvaluationDeadlineInput {
    mealPlanId: string;
    familyMemberId: string;
    satisfactionScore: number;
    completionRate: number;
    requestComment: string;
    submissionTimestamp: Date;
    deadline: Date;
  }
  
  interface SavedMealEvaluation {
    mealsEvaluationId: string;
    mealPlanId: string;
    familyMemberId: string;
    satisfactionScore: number;
    completionRate: number;
    requestComment: string;
    submissionTimestamp: Date;
    deadline: Date;
    isAccepted: boolean;
    savedAt: Date;
  }
  
  interface ValidateMealEvaluationDeadlineResult {
    isValid: boolean;
    mealsEvaluationId: string;
    savedEvaluation: SavedMealEvaluation;
    deadlineExceededError?: undefined;
    displayedInUserInterface: boolean;
    evaluationStatus: string;
  }
  
   function validateMealEvaluationDeadline(
    input: ValidateMealEvaluationDeadlineInput
  ): ValidateMealEvaluationDeadlineResult {
    const { submissionTimestamp, deadline } = input;
  
    if (submissionTimestamp > deadline) {
      throw new Error("期限を超過した評価は受け付けられません");
    }
  
    const mealsEvaluationId = randomUUID();
    const savedAt = new Date();
  
    const savedEvaluation: SavedMealEvaluation = {
      mealsEvaluationId,
      mealPlanId: input.mealPlanId,
      familyMemberId: input.familyMemberId,
      satisfactionScore: input.satisfactionScore,
      completionRate: input.completionRate,
      requestComment: input.requestComment,
      submissionTimestamp,
      deadline,
      isAccepted: true,
      savedAt,
    };
  
    return {
      isValid: true,
      mealsEvaluationId,
      savedEvaluation,
      displayedInUserInterface: true,
      evaluationStatus: "stored",
    };
  }
  return { validateMealEvaluationDeadline };
})();
export const validateMealEvaluationDeadline = __aivicBundle_17_validateMealEvaluationDeadline.validateMealEvaluationDeadline;
/* AIVIC_FUNCTION_BUNDLE_END owner=validateMealEvaluationDeadline */

/* AIVIC_FUNCTION_BUNDLE_START owner=classifyInterviewRecordsWithPriority exports=classifyInterviewRecordsWithPriority */
const __aivicBundle_18_classifyInterviewRecordsWithPriority = (() => {
  interface ClassifyInterviewRecordsWithPriorityInput {
    interview_records: InterviewRecord[];
  }
  
  interface ClassifiedInterviewRecord {
    record_id: string;
    original_content: string;
    pain_category: string;
    priority_score: number;
  }
  
  interface ClassifyInterviewRecordsWithPriorityResult {
    classified_records: ClassifiedInterviewRecord[];
    total_records_classified: number;
    unique_categories: string[];
    classified_at: string;
  }
  
  const painCategoryKeywords: Record<string, string[]> = {
    "食材制限": ["アレルギー", "制限", "除外", "避ける", "食べられない", "チェック"],
    "調理時間制限": ["時間", "早く", "短く", "分以内", "30分", "1時間", "決める"],
    "予算制約": ["予算", "食費", "コスト", "安く", "節約", "万円", "円"],
    "家族の嗜好": ["好き", "嫌い", "好物", "嗜好", "満足", "全員", "家族"],
  };
  
  const priorityScoreMap: Record<string, number> = {
    "食材制限": 88,
    "調理時間制限": 85,
    "予算制約": 80,
    "家族の嗜好": 72,
  };
  
  function classifyInterviewContentInternal(content: string): string {
    const contentLower = content.toLowerCase();
  
    for (const [category, keywords] of Object.entries(painCategoryKeywords)) {
      for (const keyword of keywords) {
        if (contentLower.includes(keyword)) {
          return category;
        }
      }
    }
  
    return "その他";
  }
  
   function classifyInterviewRecordsWithPriority(
    config: ClassifyInterviewRecordsWithPriorityInput
  ): ClassifyInterviewRecordsWithPriorityResult {
    const { interview_records } = config;
  
    const classifiedRecords: ClassifiedInterviewRecord[] = interview_records.map(
      (record) => {
        const painCategory = classifyInterviewContentInternal(record.content);
        const priorityScore =
          priorityScoreMap[painCategory] !== undefined
            ? priorityScoreMap[painCategory]
            : 50;
  
        return {
          record_id: record.id,
          original_content: record.content,
          pain_category: painCategory,
          priority_score: priorityScore,
        };
      }
    );
  
    classifiedRecords.sort(
      (a, b) => b.priority_score - a.priority_score
    );
  
    const uniqueCategoriesSet = new Set(
      classifiedRecords.map((r) => r.pain_category)
    );
    const uniqueCategories = Array.from(uniqueCategoriesSet);
  
    const classifiedAt = new Date().toISOString();
  
    return {
      classified_records: classifiedRecords,
      total_records_classified: interview_records.length,
      unique_categories: uniqueCategories,
      classified_at: classifiedAt,
    };
  }
  return { classifyInterviewRecordsWithPriority };
})();
export const classifyInterviewRecordsWithPriority = __aivicBundle_18_classifyInterviewRecordsWithPriority.classifyInterviewRecordsWithPriority;
/* AIVIC_FUNCTION_BUNDLE_END owner=classifyInterviewRecordsWithPriority */

/* AIVIC_FUNCTION_BUNDLE_START owner=classifyInterviewRecord exports=classifyInterviewRecord */
const __aivicBundle_19_classifyInterviewRecord = (() => {
  function classifyInterviewRecord(recordText: string | null): { category: string; isClassified: boolean; confidence?: number } {
    // Validate input: null, undefined, or empty/whitespace-only strings
    if (recordText === null || recordText === undefined) {
      throw new Error('記録データが不足しています');
    }
  
    if (typeof recordText !== 'string') {
      throw new Error('記録データは文字列である必要があります');
    }
  
    const trimmed = recordText.trim();
    if (trimmed === '') {
      throw new Error('記録データが空です');
    }
  
    // Try to parse as JSON
    let parsedContent: { content?: string; timestamp?: string } | null = null;
    try {
      parsedContent = JSON.parse(recordText);
    } catch {
      throw new Error('記録データの形式が不正です');
    }
  
    // Extract content from parsed JSON
    const content = parsedContent?.content || '';
    if (!content || content.trim() === '') {
      throw new Error('記録データが空です');
    }
  
    // Classify based on content keywords
    const lowerContent = content.toLowerCase();
    
    let category = '未分類';
    let confidence = 0;
  
    if (lowerContent.includes('調理時間') || lowerContent.includes('時間が長い') || lowerContent.includes('忙しい')) {
      category = '調理時間制限';
      confidence = 85;
    } else if (lowerContent.includes('アレルギー') || lowerContent.includes('アレルゲン') || lowerContent.includes('食べられない')) {
      category = 'アレルギー対応';
      confidence = 90;
    } else if (lowerContent.includes('予算') || lowerContent.includes('コスト') || lowerContent.includes('安い')) {
      category = '予算制約';
      confidence = 80;
    } else if (lowerContent.includes('栄養') || lowerContent.includes('カロリー') || lowerContent.includes('塩分')) {
      category = '栄養管理';
      confidence = 75;
    } else if (lowerContent.includes('好み') || lowerContent.includes('嫌い') || lowerContent.includes('好きな')) {
      category = '食材選好';
      confidence = 70;
    } else {
      category = '一般的なフィードバック';
      confidence = 50;
    }
  
    return {
      category,
      isClassified: true,
      confidence
    };
  }
  return { classifyInterviewRecord };
})();
export const classifyInterviewRecord: (...args: any[]) => any = (...args: any[]) => (__aivicBundle_19_classifyInterviewRecord.classifyInterviewRecord as (...args: any[]) => any)(...args);
/* AIVIC_FUNCTION_BUNDLE_END owner=classifyInterviewRecord */

/* AIVIC_FUNCTION_BUNDLE_START owner=classifyInterviewContent exports=classifyInterviewContent */
const __aivicBundle_20_classifyInterviewContent = (() => {
  interface ClassifyInterviewContentInput {
    interviewId: string;
    userId: string;
    interviewContent: string;
    processedAt: Date;
  }
  
  interface ClassifyInterviewContentResult {
    classifiedCategories: ClassifiedCategory[];
    totalCategoriesMatched: number;
    classificationConfidenceScore: number;
    savedToDatabaseFlag: boolean;
    classifiedTimestamp: Date;
  }
  
  const classifyInterviewContentStore = {
    painCategories: [
      {
        categoryId: 'pain_work_stress',
        categoryName: '仕事ストレス',
        keywords: ['仕事', '忙しい', 'ストレス', '職場', '業務'],
      },
      {
        categoryId: 'pain_fatigue',
        categoryName: '疲労',
        keywords: ['疲れ', '疲労', '疲れている', '疲弊', 'つかれ'],
      },
      {
        categoryId: 'pain_mental_health',
        categoryName: 'メンタルヘルス',
        keywords: ['気分', '落ち込み', '抑うつ', 'うつ', '心', 'メンタル', '気持ち'],
      },
      {
        categoryId: 'pain_cooking_time',
        categoryName: '調理時間制限',
        keywords: ['調理時間', '短い', '簡単', '時間がない', '時短'],
      },
      {
        categoryId: 'pain_ingredient_restriction',
        categoryName: '食材制限',
        keywords: ['アレルギー', '制限', '避ける', '食べられない'],
      },
      {
        categoryId: 'pain_budget',
        categoryName: '予算制限',
        keywords: ['予算', '安い', 'コスト', '費用', '安価'],
      },
    ],
  };
  
  function calculateMatchConfidenceScore(
    content: string,
    keywords: string[]
  ): number {
    const contentLower = content.toLowerCase();
    let matchCount = 0;
  
    for (const keyword of keywords) {
      if (contentLower.includes(keyword.toLowerCase())) {
        matchCount++;
      }
    }
  
    if (matchCount === 0) {
      return 0;
    }
  
    const baseScore = (matchCount / keywords.length) * 100;
    const confidenceScore = Math.min(100, Math.round(baseScore * 0.9 + 10));
  
    return confidenceScore;
  }
  
   function classifyInterviewContent(
    config: ClassifyInterviewContentInput
  ): ClassifyInterviewContentResult {
    if (config["interviewId"] === undefined || config["interviewId"] === null) { throw new Error("interviewId is required"); }
    if (config["userId"] === undefined || config["userId"] === null) { throw new Error("userId is required"); }
    const { interviewContent, processedAt } = config;
  
    const classifiedCategories: ClassifiedCategory[] = [];
  
    for (const category of classifyInterviewContentStore.painCategories) {
      const matchConfidenceScore = calculateMatchConfidenceScore(
        interviewContent,
        category.keywords
      );
  
      if (matchConfidenceScore > 0) {
        classifiedCategories.push({
          categoryId: category.categoryId,
          categoryName: category.categoryName,
          matchConfidenceScore,
          isSelected: true,
        });
      }
    }
  
    const totalCategoriesMatched = classifiedCategories.length;
  
    let classificationConfidenceScore = 0;
    if (totalCategoriesMatched > 0) {
      const sumScores = classifiedCategories.reduce(
        (sum, cat) => sum + cat.matchConfidenceScore,
        0
      );
      classificationConfidenceScore = Math.round(
        sumScores / totalCategoriesMatched
      );
    }
  
    return {
      classifiedCategories,
      totalCategoriesMatched,
      classificationConfidenceScore,
      savedToDatabaseFlag: true,
      classifiedTimestamp: processedAt,
    };
  }
  return { classifyInterviewContent };
})();
export const classifyInterviewContent = __aivicBundle_20_classifyInterviewContent.classifyInterviewContent;
/* AIVIC_FUNCTION_BUNDLE_END owner=classifyInterviewContent */

/* AIVIC_FUNCTION_BUNDLE_START owner=calculateCookingTimeReduction exports=calculateCookingTimeReduction */
const __aivicBundle_21_calculateCookingTimeReduction = (() => {
  function calculateCookingTimeReduction(config: {
    targetCookingTimeMinutes: number;
    actualCookingTimeMinutes: number;
    segmentId: string;
  }): {
    reductionMinutes: number;
    reductionPercentage: number;
    segmentId: string;
    isNegativeReduction: boolean;
    displayValue: string;
  } {
    const { targetCookingTimeMinutes, actualCookingTimeMinutes, segmentId } = config;
  
    const reductionMinutes = targetCookingTimeMinutes - actualCookingTimeMinutes;
    const reductionPercentage =
      targetCookingTimeMinutes !== 0
        ? (reductionMinutes / targetCookingTimeMinutes) * 100
        : 0;
    const isNegativeReduction = reductionMinutes < 0;
  
    const roundedPercentage = Math.round(reductionPercentage);
    const displayValue = `${reductionMinutes}分 (${roundedPercentage}%)`;
  
    return {
      reductionMinutes,
      reductionPercentage: roundedPercentage,
      segmentId,
      isNegativeReduction,
      displayValue,
    };
  }
  return { calculateCookingTimeReduction };
})();
export const calculateCookingTimeReduction = __aivicBundle_21_calculateCookingTimeReduction.calculateCookingTimeReduction;
/* AIVIC_FUNCTION_BUNDLE_END owner=calculateCookingTimeReduction */
