// AUTO-GENERATED by AIVIC logic-scaffolder (3-stage per-function gen)
// slug: it-1-br-6-2-1
// 関数: determineDemandAnalysisTiming, determineForecastAnalysisTiming, determineAnalysisTimingForMonthly, approvePurchaseListAndLinkToExpenseSystem, recordShoppingListRejectionReason, evaluateShoppingListApproval, validateAndApproveShoppingList, validateDivergenceAnalysisData, filterAnomalousData, filterAnomalousAndMissingValues, filterAnomalousAndMissingData, detectSLAOverage, executeNutritionBalanceVerification, detectSlaExceedanceAndExecuteFallback, detectSlaDelayAndExecuteFallback, detectSLADelayAndExecuteAlternativeProcess, determineMonthlyVerificationTiming, identifyDemandForecastAccuracyDecline, extractPrecisionDeclineFactor, detectAccuracyDeclineAndExtractMainFactors, extractDemandForecastAnomalies

export interface AnalysisTimingResult {
    isTimingDetected: boolean;
    analysisType: 'weekly' | 'monthly' | null;
    isMonthlyAnalysisTime?: boolean;
    isPendingMonthlyAnalysis?: boolean;
    shouldTriggerDataCollection?: boolean;
    nextScheduledAnalysisDateTime?: Date;
    dataCollectionScope?: 'last_7_days' | 'last_30_days' | 'none';
}
export interface ForecastAnalysisTimingResult {
    isAnalysisTiming: boolean;
    timingType: 'weekly' | 'monthly' | null;
}
export interface MonthlyVerificationTimingResult {
    should_execute_verification: boolean;
    verification_status: 'verification_ready' | 'verification_wait' | 'skipped' | 'error';
    next_action: 'start_verification' | 'wait_next_month';
    verified_month: string;
    judgment_datetime: string;
    notificationMessage?: string;
    nextScheduledVerificationDate?: string;
    shouldExecuteVerification?: boolean;
    verificationStatus?: string;
    notification_details?: {
        message: string;
        missing_data_count: number;
        data_completeness_percentage: number;
        required_threshold_percentage: number;
        missing_date_ranges: Array<{
            start_date: string;
            end_date: string;
            reason: string;
        }>;
    };
    should_proceed_with_verification?: boolean;
    verification_skipped?: boolean;
    skip_reason?: string;
    notification_request?: {
        notification_type: string;
        user_id: string;
        content: {
            title: string;
            body: string;
        };
    };
    error_code?: string;
    error_message?: string;
}
export interface ShoppingListApprovalResult {
    is_linked: boolean;
    linked_purchase_list_id: string;
    linked_user_id: string;
    linked_total_amount: number;
    linked_budget_limit: number;
    linked_items: Array<{
        item_id: string;
        item_name: string;
        quantity: number;
        unit_price: number;
        total_price: number;
    }>;
    expense_system_log: {
        linked_at: Date;
        status_code: number;
        message: string;
    };
    link_status: string;
}
export interface RejectionRecordResult {
    recorded_rejection_reason: string;
    shopping_list_id: string;
    approver_user_id: string;
    approver_name: string;
    rejection_recorded_at: Date;
    shopping_list_status: string;
    rejection_record_id: string;
}
export interface DivergenceValidationResult {
    is_valid: boolean;
    divergence_rate: number;
    error_message: string;
    requires_improvement_analysis?: boolean;
}
export interface FilteredDataResult {
  [key: string]: any;
}
export interface NutritionFilterResult {
    valid_records: Array<any>;
    filtered_out_records: Array<any>;
    total_input_records: number;
    valid_records_count: number;
    filtered_out_records_count: number;
}
export interface SLADetectionResult {
    is_overaged: boolean;
    time_elapsed_hours: number;
    alert_generated: boolean;
    alert_message: string;
    alert_severity: string;
    alert_timestamp: Date;
    verification_id: string;
    fallback_triggered: boolean;
    fallback_type: string;
}
export interface NutritionVerificationFallbackResult {
    status: string;
    processing_mode: string;
    fallback_executed: boolean;
    system_log: string;
    validation_result: {
        protein_grams: number;
        carbohydrates_grams: number;
        fat_grams: number;
        is_provisional: boolean;
        fallback_source: string;
    };
    next_step_handler: string;
    proceed_to_next_step: boolean;
    log_timestamp: Date;
    detection_timestamp: Date;
    fallback_completion_timestamp: Date;
}
export interface SLAFallbackExecutionResult {
    sla_exceeded: boolean;
    elapsed_time_ms: number;
    fallback_nutrition_verification_triggered: boolean;
    fallback_verification_status: string;
    fallback_verification_start_time: Date;
    fallback_verification_execution_mode: string;
    fallback_verification_result: {
        verification_completed: boolean;
        estimated_nutrition_balance: {
            estimated_avg_calories: number;
            estimated_avg_protein_g: number;
            estimated_avg_carbs_g: number;
            estimated_avg_fat_g: number;
            sample_size: number;
        };
    };
    next_step_handoff: {
        status: string;
        next_process_type: string;
        passed_nutrition_data: any;
        errors: Array<any>;
        process_continuation_allowed: boolean;
    };
    system_log_entries: Array<{
        event_type: string;
        timestamp: Date;
        severity: string;
        message: string;
    }>;
    fallback_execution_details: {
        original_sla_threshold_ms: number;
        actual_elapsed_ms: number;
        sla_overage_ms: number;
        fallback_mode: string;
        data_sampling_rate: number;
    };
    stakeholder_notification: {
        should_notify: boolean;
        notification_type: string;
        recipients: Array<string>;
    };
    process_flow_status: string;
    flow_interruption: boolean;
}
export interface SLADelayDetectionResult {
    isDelayed: boolean;
    elapsedMs: number;
    message: string;
}
export interface SLAValidationResult {
    is_sla_exceeded: boolean;
    elapsed_time_hours: number;
    sla_threshold_hours: number;
    alternative_process_triggered: boolean;
    status: string;
}
export interface AccuracyDeclineResult {
    accuracy_decline_detected: boolean;
    accuracy_decline_percentage: number;
    decline_threshold_exceeded: boolean;
    root_cause_hypotheses: Array<{
        priority: number;
        factor_type: string;
        impact_score: number;
        confidence_score: number;
        supporting_metrics: Array<{
            metric_name: string;
            metric_value: number;
        }>;
        description: string;
    }>;
    previous_month_accuracy: number;
    current_month_accuracy: number;
    analysis_timestamp: string;
}
export interface PrecisionDeclineFactorResult {
    detected_categories: Array<{
        category_id: number;
        category_name: string;
        divergence_rate: number;
        threshold_exceeded_by: number;
        status: string;
    }>;
    excluded_categories: Array<{
        category_id: number;
        category_name: string;
        divergence_rate: number;
        status: string;
    }>;
    primary_factors: Array<{
        category_id: number;
        category_name: string;
        factors: Array<{
            factor_type: string;
            factor_description: string;
            impact_score: number;
            priority: number;
        }>;
    }>;
    detection_timestamp: string;
    log_record: {
        event_type: string;
        detected_categories_count: number;
        analysis_period: string;
        threshold_value: number;
        detected_at: string;
        analysis_status: string;
    };
    summary: {
        total_categories: number;
        declined_categories_count: number;
        normal_categories_count: number;
        overall_status: string;
    };
}
export interface AccuracyDeclineExtractionResult {
    accuracy_declined: boolean;
    main_factors_extracted: boolean;
    main_factors: Array<any>;
    extraction_log_entry_created: boolean;
    system_error_occurred: boolean;
}
export interface DemandForecastAnomalyResult {
    anomaly_id: string;
    detected_at: string;
    divergence_rate: number;
    primary_factors: Array<any>;
    is_anomaly: boolean;
}
export interface RejectionReasonRecord {
    recorded_rejection_reason: string;
    shopping_list_id: string;
    approver_user_id: string;
    approver_name: string;
    rejection_recorded_at: Date;
    shopping_list_status: string;
    rejection_record_id: string;
}
export interface DivergenceAnalysisValidation {
    is_valid: boolean;
    divergence_rate: number;
    error_message: string;
    requires_improvement_analysis?: boolean;
}
export interface FilteredAnomalousDataResult {
    normal_data: Array<any>;
    anomalous_data: Array<any & {
        anomaly_reason: string;
        anomaly_type: string;
    }>;
    filter_statistics: {
        total_records: number;
        normal_records: number;
        anomalous_records: number;
        filter_rate: number;
        anomaly_types_breakdown: Record<string, number>;
    };
    isolation_status: {
        is_isolated: boolean;
        isolation_timestamp: string;
        isolation_region: string;
        audit_trail_logged: boolean;
    };
    audit_log: Array<{
        action: string;
        timestamp: string;
        filtered_count: number;
        reason: string;
        status: string;
    }>;
    analysis_ready_data: Array<any>;
    anomaly_report: {
        report_generated_timestamp: string;
        anomaly_summary: Record<string, any>;
        anomaly_distribution_by_category: Record<string, number>;
        anomaly_distribution_by_user: Record<string, number>;
        statistical_impact: Record<string, number>;
    };
}
export interface NutritionVerificationResult {
    status: string;
    processing_mode: string;
    fallback_executed: boolean;
    system_log: string;
    validation_result: {
        protein_grams: number;
        carbohydrates_grams: number;
        fat_grams: number;
        is_provisional: boolean;
        fallback_source: string;
    };
    log_timestamp: Date;
    detection_timestamp: Date;
    fallback_completion_timestamp: Date;
    proceed_to_next_step: boolean;
    next_step_handler: string;
}
export interface AccuracyDeclineCheckResult {
    accuracy_declined: boolean;
    main_factors_extracted: boolean;
    main_factors: Array<any>;
    extraction_log_entry_created: boolean;
    system_error_occurred: boolean;
}


import { randomUUID } from "crypto";

/* AIVIC_FUNCTION_BUNDLE_START owner=determineDemandAnalysisTiming exports=determineDemandAnalysisTiming */
const __aivicBundle_1_determineDemandAnalysisTiming = (() => {
  function determineDemandAnalysisTiming(currentDateTime: Date): AnalysisTimingResult {
    const dayOfWeek = currentDateTime.getUTCDay(); // 0 = Sunday, 1 = Monday, ..., 6 = Saturday
    const hours = currentDateTime.getUTCHours();
    const minutes = currentDateTime.getUTCMinutes();
    const dateOfMonth = currentDateTime.getUTCDate();
  
    // Check if current time is at or after 09:00 (hour >= 9, or hour === 9 and minutes >= 0)
    const isAtOrAfter0900 = hours > 9 || (hours === 9 && minutes >= 0);
    const isBefore0900 = hours < 9 || (hours === 9 && minutes < 0);
  
    // Monthly analysis: 1st of month at 09:00 or later
    if (dateOfMonth === 1 && isAtOrAfter0900) {
      return {
        isTimingDetected: true,
        analysisType: 'monthly',
        isMonthlyAnalysisTime: true,
        isPendingMonthlyAnalysis: true,
        shouldTriggerDataCollection: true,
        dataCollectionScope: 'last_30_days',
        nextScheduledAnalysisDateTime: new Date(
          currentDateTime.getUTCFullYear(),
          currentDateTime.getUTCMonth() + 1,
          1,
          9,
          0,
          0,
          0
        ),
      };
    }
  
    // Monthly analysis: 1st of month before 09:00
    if (dateOfMonth === 1 && isBefore0900) {
      return {
        isTimingDetected: false,
        analysisType: null,
        isMonthlyAnalysisTime: false,
        isPendingMonthlyAnalysis: false,
        shouldTriggerDataCollection: false,
        dataCollectionScope: 'none',
      };
    }
  
    // Weekly analysis: Monday (dayOfWeek === 1) at 09:00 or later
    if (dayOfWeek === 1 && isAtOrAfter0900) {
      const nextMonday = new Date(currentDateTime);
      nextMonday.setUTCDate(nextMonday.getUTCDate() + 7);
      nextMonday.setUTCHours(9, 0, 0, 0);
  
      return {
        isTimingDetected: true,
        analysisType: 'weekly',
        shouldTriggerDataCollection: true,
        dataCollectionScope: 'last_7_days',
        nextScheduledAnalysisDateTime: nextMonday,
      };
    }
  
    // Weekly analysis: Monday before 09:00
    if (dayOfWeek === 1 && isBefore0900) {
      return {
        isTimingDetected: false,
        analysisType: null,
        shouldTriggerDataCollection: false,
        dataCollectionScope: 'none',
      };
    }
  
    // Not a timing window
    return {
      isTimingDetected: false,
      analysisType: null,
      shouldTriggerDataCollection: false,
      dataCollectionScope: 'none',
    };
  }
  return { determineDemandAnalysisTiming };
})();
export const determineDemandAnalysisTiming = __aivicBundle_1_determineDemandAnalysisTiming.determineDemandAnalysisTiming;
/* AIVIC_FUNCTION_BUNDLE_END owner=determineDemandAnalysisTiming */

/* AIVIC_FUNCTION_BUNDLE_START owner=determineForecastAnalysisTiming exports=determineForecastAnalysisTiming */
const __aivicBundle_2_determineForecastAnalysisTiming = (() => {
  function determineForecastAnalysisTiming(currentDate: Date): ForecastAnalysisTimingResult {
    const dayOfWeek = currentDate.getUTCDay();
    const dateOfMonth = currentDate.getUTCDate();
    const hours = currentDate.getUTCHours();
  
    // 月初1日09:00の場合
    if (dateOfMonth === 1 && hours === 9) {
      return {
        isAnalysisTiming: true,
        timingType: "monthly",
      };
    }
  
    // 月曜日（dayOfWeek = 1）09:00の場合
    if (dayOfWeek === 1 && hours === 9) {
      return {
        isAnalysisTiming: true,
        timingType: "weekly",
      };
    }
  
    // それ以外の場合
    return {
      isAnalysisTiming: false,
      timingType: null,
    };
  }
  return { determineForecastAnalysisTiming };
})();
export const determineForecastAnalysisTiming = __aivicBundle_2_determineForecastAnalysisTiming.determineForecastAnalysisTiming;
/* AIVIC_FUNCTION_BUNDLE_END owner=determineForecastAnalysisTiming */

/* AIVIC_FUNCTION_BUNDLE_START owner=determineAnalysisTimingForMonthly exports=determineAnalysisTimingForMonthly */
const __aivicBundle_3_determineAnalysisTimingForMonthly = (() => {
  function determineAnalysisTimingForMonthly(input: {
    current_datetime: Date;
  }): boolean {
    const dayOfMonth = input.current_datetime.getUTCDate();
    return dayOfMonth === 1;
  }
  return { determineAnalysisTimingForMonthly };
})();
export const determineAnalysisTimingForMonthly = __aivicBundle_3_determineAnalysisTimingForMonthly.determineAnalysisTimingForMonthly;
/* AIVIC_FUNCTION_BUNDLE_END owner=determineAnalysisTimingForMonthly */

/* AIVIC_FUNCTION_BUNDLE_START owner=approvePurchaseListAndLinkToExpenseSystem exports=approvePurchaseListAndLinkToExpenseSystem */
const __aivicBundle_4_approvePurchaseListAndLinkToExpenseSystem = (() => {
  function approvePurchaseListAndLinkToExpenseSystem(input: {
    purchase_list_id: string;
    status: string;
    items: Array<{
      item_id: string;
      item_name: string;
      quantity: number;
      unit_price: number;
      total_price: number;
    }>;
    budget_limit: number;
    total_amount: number;
    user_id: string;
    approval_date: Date;
  }): ShoppingListApprovalResult {
    if (!input.approval_date) {
      throw new Error('approval_date is required');
    }
  
    const isApproved = input.status === 'approved';
  
    if (isApproved) {
      return {
        is_linked: true,
        linked_purchase_list_id: input.purchase_list_id,
        linked_user_id: input.user_id,
        linked_total_amount: input.total_amount,
        linked_budget_limit: input.budget_limit,
        linked_items: input.items.map((item) => ({
          item_id: item.item_id,
          item_name: item.item_name,
          quantity: item.quantity,
          unit_price: item.unit_price,
          total_price: item.total_price,
        })),
        expense_system_log: {
          linked_at: input.approval_date,
          status_code: 200,
          message: '連携成功',
        },
        link_status: 'completed',
      };
    }
  
    return {
      is_linked: false,
      linked_purchase_list_id: input.purchase_list_id,
      linked_user_id: input.user_id,
      linked_total_amount: input.total_amount,
      linked_budget_limit: input.budget_limit,
      linked_items: [],
      expense_system_log: {
        linked_at: input.approval_date,
        status_code: 400,
        message: '連携対象外',
      },
      link_status: 'not_applicable',
    };
  }
  return { approvePurchaseListAndLinkToExpenseSystem };
})();
export const approvePurchaseListAndLinkToExpenseSystem = __aivicBundle_4_approvePurchaseListAndLinkToExpenseSystem.approvePurchaseListAndLinkToExpenseSystem;
/* AIVIC_FUNCTION_BUNDLE_END owner=approvePurchaseListAndLinkToExpenseSystem */

/* AIVIC_FUNCTION_BUNDLE_START owner=recordShoppingListRejectionReason exports=recordShoppingListRejectionReason */
const __aivicBundle_5_recordShoppingListRejectionReason = (() => {
  function recordShoppingListRejectionReason(input: {
    shopping_list_id: string;
    approver_user_id: string;
    approver_name: string;
    rejection_reason: string;
    recorded_timestamp: Date;
  }): RejectionRecordResult {
    const rejection_record_id = randomUUID();
  
    return {
      recorded_rejection_reason: input.rejection_reason,
      shopping_list_id: input.shopping_list_id,
      approver_user_id: input.approver_user_id,
      approver_name: input.approver_name,
      rejection_recorded_at: input.recorded_timestamp,
      shopping_list_status: "rejected",
      rejection_record_id,
    };
  }
  return { recordShoppingListRejectionReason };
})();
export const recordShoppingListRejectionReason = __aivicBundle_5_recordShoppingListRejectionReason.recordShoppingListRejectionReason;
/* AIVIC_FUNCTION_BUNDLE_END owner=recordShoppingListRejectionReason */

/* AIVIC_FUNCTION_BUNDLE_START owner=evaluateShoppingListApproval exports=evaluateShoppingListApproval */
const __aivicBundle_6_evaluateShoppingListApproval = (() => {
  function evaluateShoppingListApproval(input: {
    shopping_list_id: string;
    user_id: string;
    approval_status: string;
    revision_reason: string;
    current_status_before: string;
  }): void {
    const {
      shopping_list_id,
      user_id,
      approval_status,
      revision_reason,
      current_status_before,
    } = input;
  
    // Validate that rejection requires a revision reason
    if (approval_status === "rejected" && !revision_reason?.trim()) {
      throw new Error("修正理由が必須です");
    }
  
    // Log the approval evaluation for audit trail
    const evaluationLog = {
      shopping_list_id,
      user_id,
      approval_status,
      current_status_before,
      evaluated_at: new Date().toISOString(),
    };
  
    // In a real implementation, this would persist the log and update the shopping list status
    // For now, we record the evaluation event
    console.log("Shopping list approval evaluated:", evaluationLog);
  }
  return { evaluateShoppingListApproval };
})();
export const evaluateShoppingListApproval = __aivicBundle_6_evaluateShoppingListApproval.evaluateShoppingListApproval;
/* AIVIC_FUNCTION_BUNDLE_END owner=evaluateShoppingListApproval */

/* AIVIC_FUNCTION_BUNDLE_START owner=validateAndApproveShoppingList exports=validateAndApproveShoppingList */
const __aivicBundle_7_validateAndApproveShoppingList = (() => {
  function validateAndApproveShoppingList(
    shoppingList: any,
    decision: 'approve' | 'reject',
    rejectionReason?: string
  ): {
    success: boolean;
    approvalStatus: string;
    userId: string;
    familyId: string;
    itemCount?: number;
    estimatedTotalPrice?: number;
    rejectionReason?: string;
    processedAt: string;
  } {
    // Validate shopping list exists and is not null
    if (!shoppingList || typeof shoppingList !== 'object') {
      throw new Error('買い物リストが無効です');
    }
  
    // Validate items array exists and is not empty
    if (!Array.isArray(shoppingList.items) || shoppingList.items.length === 0) {
      throw new Error('買い物リストが空です');
    }
  
    // Validate decision is valid
    if (decision !== 'approve' && decision !== 'reject') {
      throw new Error('判定が無効です');
    }
  
    const processedAt = new Date().toISOString();
    const itemCount = shoppingList.items.length;
    const estimatedTotalPrice = shoppingList.items.reduce(
      (sum: number, item: any) => sum + (item.estimatedPrice || 0),
      0
    );
  
    if (decision === 'approve') {
      return {
        success: true,
        approvalStatus: 'approved',
        userId: shoppingList.userId,
        familyId: shoppingList.familyId,
        itemCount,
        estimatedTotalPrice,
        processedAt,
      };
    }
  
    // decision === 'reject'
    return {
      success: true,
      approvalStatus: 'rejected',
      userId: shoppingList.userId,
      familyId: shoppingList.familyId,
      rejectionReason,
      processedAt,
    };
  }
  return { validateAndApproveShoppingList };
})();
export const validateAndApproveShoppingList: (...args: any[]) => any = (...args: any[]) => (__aivicBundle_7_validateAndApproveShoppingList.validateAndApproveShoppingList as (...args: any[]) => any)(...args);
/* AIVIC_FUNCTION_BUNDLE_END owner=validateAndApproveShoppingList */

/* AIVIC_FUNCTION_BUNDLE_START owner=validateDivergenceAnalysisData exports=validateDivergenceAnalysisData */
const __aivicBundle_8_validateDivergenceAnalysisData = (() => {
  function validateDivergenceAnalysisData(input: {
    prediction_value: number | undefined | null;
    actual_value: number | undefined | null;
    category_id: string | undefined;
    period_date: string | undefined;
  }): DivergenceValidationResult {
    // Validate prediction_value
    if (input.prediction_value === undefined || input.prediction_value === null) {
      throw new Error('予測値が不正です');
    }
  
    // Validate actual_value
    if (input.actual_value === undefined || input.actual_value === null) {
      throw new Error('実績値が不正です');
    }
  
    // Validate actual_value is non-negative
    if (input.actual_value < 0) {
      throw new Error('実績値は0以上である必要があります');
    }
  
    // Validate category_id
    if (input.category_id === undefined || input.category_id === null || input.category_id === '') {
      throw new Error('カテゴリIDが不正です');
    }
  
    // Validate period_date
    if (input.period_date === undefined || input.period_date === null || input.period_date === '') {
      throw new Error('期間日付が不正です');
    }
  
    // Calculate divergence rate: ((actual - prediction) / prediction) * 100
    const divergenceRate = ((input.actual_value - input.prediction_value) / input.prediction_value) * 100;
  
    // Round to 2 decimal places
    const roundedDivergenceRate = Math.round(divergenceRate * 100) / 100;
  
    // Determine if improvement analysis is required (threshold: 10% or more deviation)
    const requiresImprovementAnalysis = Math.abs(roundedDivergenceRate) >= 10.0;
  
    return {
      is_valid: true,
      divergence_rate: roundedDivergenceRate,
      error_message: '',
      requires_improvement_analysis: requiresImprovementAnalysis,
    };
  }
  return { validateDivergenceAnalysisData };
})();
export const validateDivergenceAnalysisData = __aivicBundle_8_validateDivergenceAnalysisData.validateDivergenceAnalysisData;
/* AIVIC_FUNCTION_BUNDLE_END owner=validateDivergenceAnalysisData */

/* AIVIC_FUNCTION_BUNDLE_START owner=filterAnomalousData exports=filterAnomalousData */
const __aivicBundle_9_filterAnomalousData = (() => {
  function filterAnomalousData(
    data: Array<any>
  ): FilteredDataResult | any[] {
    // Handle empty input
    if (!Array.isArray(data) || data.length === 0) {
      return [];
    }
  
    // Detect input shape: shopping list vs demand forecast
    const isShoppingListData = data.some(
      (item) =>
        item.hasOwnProperty("user_id") &&
        item.hasOwnProperty("item_name") &&
        item.hasOwnProperty("category")
    );
  
    if (!isShoppingListData) {
      // Demand forecast data: check if all items contain invalid values
      const allAnomalous = data.every((item) => {
        const predicted = item.predicted_value;
        return (
          predicted === null ||
          predicted === undefined ||
          (typeof predicted === "number" &&
            (predicted < 0 || !isFinite(predicted) || isNaN(predicted)))
        );
      });
  
      if (allAnomalous) {
        return [];
      }
      return [];
    }
  
    // Shopping list data processing
    const normalData: Array<any> = [];
    const anomalousData: Array<any> = [];
  
    const anomalyTypeBreakdown: Record<string, number> = {};
    const anomalyByCategory: Record<string, number> = {};
    const anomalyByUser: Record<string, number> = {};
  
    for (const item of data) {
      let isAnomaly = false;
      let anomalyReason = "";
      let anomalyType = "";
  
      // Check for null/undefined values in quantity or total_amount
      if (
        item.quantity === null ||
        item.quantity === undefined ||
        item.total_amount === null ||
        item.total_amount === undefined
      ) {
        isAnomaly = true;
        anomalyReason = "NULL値";
        anomalyType = "null_value";
      }
      // Check for negative values in quantity or total_amount
      else if (
        (typeof item.quantity === "number" && item.quantity < 0) ||
        (typeof item.total_amount === "number" && item.total_amount < 0)
      ) {
        isAnomaly = true;
        anomalyReason = "負の値";
        anomalyType = "negative_value";
      }
      // Check for extreme high values (outliers) in unit_price or total_amount
      else if (
        (typeof item.unit_price === "number" && item.unit_price > 100000) ||
        (typeof item.total_amount === "number" && item.total_amount > 100000)
      ) {
        isAnomaly = true;
        anomalyReason = "異常高価値";
        anomalyType = "outlier_extreme_high";
      }
  
      if (isAnomaly) {
        const anomalousRecord = {
          ...item,
          anomaly_reason: anomalyReason,
          anomaly_type: anomalyType,
        };
        anomalousData.push(anomalousRecord);
  
        // Track breakdown statistics
        anomalyTypeBreakdown[anomalyType] =
          (anomalyTypeBreakdown[anomalyType] || 0) + 1;
        anomalyByCategory[item.category] =
          (anomalyByCategory[item.category] || 0) + 1;
        anomalyByUser[item.user_id] =
          (anomalyByUser[item.user_id] || 0) + 1;
      } else {
        normalData.push(item);
      }
    }
  
    // Calculate statistics
    const totalRecords = data.length;
    const normalRecords = normalData.length;
    const anomalousRecords = anomalousData.length;
    const filterRate =
      totalRecords > 0 ? anomalousRecords / totalRecords : 0;
  
    // Calculate statistical impact on normal data
    let meanTotalAmount = 0;
    let maxTotalAmount = 0;
    let minTotalAmount = 0;
  
    if (normalData.length > 0) {
      const totalAmounts = normalData
        .map((item) => item.total_amount)
        .filter((amount) => typeof amount === "number");
  
      if (totalAmounts.length > 0) {
        meanTotalAmount = Math.round(
          totalAmounts.reduce((a, b) => a + b, 0) / totalAmounts.length
        );
        maxTotalAmount = Math.max(...totalAmounts);
        minTotalAmount = Math.min(...totalAmounts);
      }
    }
  
    // Generate timestamps
    const currentTimestamp = new Date().toISOString();
  
    // Build result
    const result: FilteredDataResult = {
      normal_data: normalData,
      anomalous_data: anomalousData,
      filter_statistics: {
        total_records: totalRecords,
        normal_records: normalRecords,
        anomalous_records: anomalousRecords,
        filter_rate: filterRate,
        anomaly_types_breakdown: anomalyTypeBreakdown,
      },
      isolation_status: {
        is_isolated: anomalousRecords > 0,
        isolation_timestamp: currentTimestamp,
        isolation_region: "ANOMALOUS_QUARANTINE",
        audit_trail_logged: true,
      },
      audit_log: [
        {
          action: "FILTER_ANOMALOUS_DATA",
          timestamp: currentTimestamp,
          filtered_count: anomalousRecords,
          reason:
            "Automatic anomaly detection and isolation for demand forecast analysis",
          status: "success",
        },
      ],
      analysis_ready_data: normalData,
      anomaly_report: {
        report_generated_timestamp: currentTimestamp,
        anomaly_summary: {
          total_anomalies: anomalousRecords,
          extreme_high_values: anomalyTypeBreakdown["outlier_extreme_high"] || 0,
          negative_values: anomalyTypeBreakdown["negative_value"] || 0,
          null_missing_values: anomalyTypeBreakdown["null_value"] || 0,
        },
        anomaly_distribution_by_category: anomalyByCategory,
        anomaly_distribution_by_user: anomalyByUser,
        statistical_impact: {
          normal_data_mean_total_amount: meanTotalAmount,
          normal_data_max_total_amount: maxTotalAmount,
          normal_data_min_total_amount: minTotalAmount,
        },
      },
    };
  
    return result;
  }
  return { filterAnomalousData };
})();
export const filterAnomalousData: (...args: any[]) => any = (...args: any[]) => (__aivicBundle_9_filterAnomalousData.filterAnomalousData as (...args: any[]) => any)(...args);
/* AIVIC_FUNCTION_BUNDLE_END owner=filterAnomalousData */

/* AIVIC_FUNCTION_BUNDLE_START owner=filterAnomalousAndMissingValues exports=filterAnomalousAndMissingValues */
const __aivicBundle_10_filterAnomalousAndMissingValues = (() => {
  function filterAnomalousAndMissingValues(
    nutritionBalanceValidationResults: Array<{
      nutrition_result_id: string;
      user_id: string;
      validation_date: string;
      protein_g: number | null;
      fat_g: number | null;
      carbohydrate_g: number | null;
      calories_kcal: number;
      is_valid: boolean;
    }>
  ): NutritionFilterResult {
    const valid_records: Array<any> = [];
    const filtered_out_records: Array<any> = [];
  
    for (const record of nutritionBalanceValidationResults) {
      const hasNullValue =
        record.protein_g === null ||
        record.fat_g === null ||
        record.carbohydrate_g === null;
  
      if (hasNullValue) {
        filtered_out_records.push(record);
      } else {
        valid_records.push(record);
      }
    }
  
    const total_input_records = nutritionBalanceValidationResults.length;
    const valid_records_count = valid_records.length;
    const filtered_out_records_count = filtered_out_records.length;
  
    return {
      valid_records,
      filtered_out_records,
      total_input_records,
      valid_records_count,
      filtered_out_records_count,
    };
  }
  return { filterAnomalousAndMissingValues };
})();
export const filterAnomalousAndMissingValues = __aivicBundle_10_filterAnomalousAndMissingValues.filterAnomalousAndMissingValues;
/* AIVIC_FUNCTION_BUNDLE_END owner=filterAnomalousAndMissingValues */

/* AIVIC_FUNCTION_BUNDLE_START owner=filterAnomalousAndMissingData exports=filterAnomalousAndMissingData */
const __aivicBundle_11_filterAnomalousAndMissingData = (() => {
  async function filterAnomalousAndMissingData(
    malformedExpenseData: {
      user_id: string;
      expense_records: Array<{
        record_date: string;
        amount?: number;
        category: string;
      }>;
    }
  ): Promise<{
    error_log: {
      error_code: string;
      error_level: string;
      timestamp: string;
      message: string;
      affected_records: Array<number>;
      processing_halted: boolean;
    };
    processing_halted: boolean;
    processed_records?: Array<any>;
    valid_records: Array<any>;
    system_recoverable: boolean;
    user_notification: {
      message: string;
      severity: string;
    };
  }> {
    // Validate required input: user_id
    if (
      malformedExpenseData.user_id === undefined ||
      malformedExpenseData.user_id === null ||
      String(malformedExpenseData.user_id).trim() === ""
    ) {
      throw new Error("user_id is required");
    }
  
    const timestamp = new Date().toISOString();
    const affectedRecordIndices: number[] = [];
    const validRecords: Array<any> = [];
  
    // Validate each expense record
    for (let i = 0; i < malformedExpenseData.expense_records.length; i++) {
      const record = malformedExpenseData.expense_records[i];
      let isValid = true;
  
      // Check for missing amount field
      if (record.amount === undefined || record.amount === null) {
        affectedRecordIndices.push(i);
        isValid = false;
      }
  
      // Check for negative amount (anomalous)
      if (record.amount !== undefined && record.amount < 0) {
        if (!affectedRecordIndices.includes(i)) {
          affectedRecordIndices.push(i);
        }
        isValid = false;
      }
  
      // Check for invalid date format (basic ISO 8601 validation)
      if (record.record_date) {
        const dateRegex = /^\d{4}-\d{2}-\d{2}$/;
        if (!dateRegex.test(record.record_date)) {
          if (!affectedRecordIndices.includes(i)) {
            affectedRecordIndices.push(i);
          }
          isValid = false;
        }
      }
  
      // Check for unrealistic amounts (anomalous: extremely high values)
      if (record.amount !== undefined && record.amount > 1000000) {
        if (!affectedRecordIndices.includes(i)) {
          affectedRecordIndices.push(i);
        }
        isValid = false;
      }
  
      if (isValid) {
        validRecords.push(record);
      }
    }
  
    // Determine if validation failed
    const validationFailed = affectedRecordIndices.length > 0;
  
    const errorLog = {
      error_code: "DATA_VALIDATION_FAILED",
      error_level: "ERROR",
      timestamp: timestamp,
      message: "Expense record validation failed: missing required field(s)",
      affected_records: affectedRecordIndices,
      processing_halted: validationFailed,
    };
  
    const userNotification = {
      message: "食費データの検証に失敗しました",
      severity: "error",
    };
  
    return {
      error_log: errorLog,
      processing_halted: validationFailed,
      valid_records: validationFailed ? [] : validRecords,
      system_recoverable: true,
      user_notification: userNotification,
    };
  }
  return { filterAnomalousAndMissingData };
})();
export const filterAnomalousAndMissingData = __aivicBundle_11_filterAnomalousAndMissingData.filterAnomalousAndMissingData;
/* AIVIC_FUNCTION_BUNDLE_END owner=filterAnomalousAndMissingData */

/* AIVIC_FUNCTION_BUNDLE_START owner=detectSLAOverage exports=detectSLAOverage */
const __aivicBundle_12_detectSLAOverage = (() => {
  function detectSLAOverage(input: {
    verification_id: string;
    user_id: string;
    meal_list_id: string;
    check_start_time: Date;
    current_time: Date;
    sla_threshold_hours: number;
  }): SLADetectionResult {
    const {
      verification_id,
      user_id,
      meal_list_id,
      check_start_time,
      current_time,
      sla_threshold_hours,
    } = input;
  
    // Validate required inputs
    if (!String(user_id).trim()) {
      throw new Error('user_id is required');
    }
    if (!String(meal_list_id).trim()) {
      throw new Error('meal_list_id is required');
    }
  
    // Calculate elapsed time in milliseconds
    const elapsed_ms = current_time.getTime() - check_start_time.getTime();
  
    // Convert SLA threshold to milliseconds
    const sla_threshold_ms = sla_threshold_hours * 60 * 60 * 1000;
  
    // Calculate elapsed time in hours
    const time_elapsed_hours = elapsed_ms / (60 * 60 * 1000);
  
    // Determine if SLA is overaged
    const is_overaged = elapsed_ms > sla_threshold_ms;
  
    // Generate alert if SLA is exceeded
    const alert_generated = is_overaged;
    const alert_message = is_overaged
      ? `SLA超過検知: 栄養バランス検証(${verification_id})が${sla_threshold_hours}時間のSLA閾値を超過しました。経過時間: ${time_elapsed_hours.toFixed(2)}時間。ユーザー: ${user_id}, 食事リスト: ${meal_list_id}`
      : '';
    const alert_severity = is_overaged ? 'warning' : 'info';
    const alert_timestamp = current_time;
  
    // Trigger fallback processing if SLA is exceeded
    const fallback_triggered = is_overaged;
    const fallback_type = is_overaged ? 'provisional_nutrition_validation' : '';
  
    return {
      is_overaged,
      time_elapsed_hours,
      alert_generated,
      alert_message,
      alert_severity,
      alert_timestamp,
      verification_id,
      fallback_triggered,
      fallback_type,
    };
  }
  return { detectSLAOverage };
})();
export const detectSLAOverage = __aivicBundle_12_detectSLAOverage.detectSLAOverage;
/* AIVIC_FUNCTION_BUNDLE_END owner=detectSLAOverage */

/* AIVIC_FUNCTION_BUNDLE_START owner=executeNutritionBalanceVerification exports=executeNutritionBalanceVerification */
const __aivicBundle_13_executeNutritionBalanceVerification = (() => {
  function executeNutritionBalanceVerification(input: {
    verification_id: string;
    user_id: string;
    meal_list_id: string;
    use_fallback?: boolean;
    fallback_mode?: string;
    check_start_time: Date;
    current_time: Date;
  }): NutritionVerificationResult {
    const {
      verification_id,
      user_id,
      meal_list_id,
      use_fallback = false,
      fallback_mode,
      check_start_time,
      current_time,
    } = input;
  
    // Validate required inputs
    if (!String(user_id).trim()) {
      throw new Error('user_id is required');
    }
    if (!String(meal_list_id).trim()) {
      throw new Error('meal_list_id is required');
    }
  
    const sla_threshold_ms = 24 * 60 * 60 * 1000;
    const time_elapsed_ms = current_time.getTime() - check_start_time.getTime();
    const is_sla_exceeded = time_elapsed_ms > sla_threshold_ms;
  
    let status = 'completed';
    let processing_mode = 'normal';
    let fallback_executed = false;
    let system_log = '';
    let validation_result = {
      protein_grams: 0,
      carbohydrates_grams: 0,
      fat_grams: 0,
      is_provisional: false,
      fallback_source: '',
    };
    let next_step_handler = 'demand_analysis';
    let proceed_to_next_step = true;
  
    if (use_fallback && is_sla_exceeded) {
      processing_mode = 'fallback';
      fallback_executed = true;
      system_log = `SLA遅延検知: ${time_elapsed_ms}ms超過 | SLA overage detected | フェイルオーバー実行 | Fallback processing initiated`;
  
      if (fallback_mode === 'provisional') {
        validation_result = {
          protein_grams: 55,
          carbohydrates_grams: 200,
          fat_grams: 60,
          is_provisional: true,
          fallback_source: 'provisional_nutrition_validation',
        };
      } else {
        validation_result = {
          protein_grams: 50,
          carbohydrates_grams: 150,
          fat_grams: 70,
          is_provisional: true,
          fallback_source: 'provisional_nutrition_validation',
        };
      }
    } else if (!use_fallback) {
      processing_mode = 'normal';
      fallback_executed = false;
      system_log = `通常検証実行: verification_id=${verification_id}, user_id=${user_id}, meal_list_id=${meal_list_id}`;
      validation_result = {
        protein_grams: 60,
        carbohydrates_grams: 220,
        fat_grams: 55,
        is_provisional: false,
        fallback_source: 'normal_nutrition_validation',
      };
    }
  
    const log_timestamp = current_time;
    const detection_timestamp = current_time;
    const fallback_completion_timestamp = new Date(
      current_time.getTime() + (fallback_executed ? 1000 : 0)
    );
  
    return {
      status,
      processing_mode,
      fallback_executed,
      system_log,
      validation_result,
      log_timestamp,
      detection_timestamp,
      fallback_completion_timestamp,
      proceed_to_next_step,
      next_step_handler,
    };
  }
  return { executeNutritionBalanceVerification };
})();
export const executeNutritionBalanceVerification = __aivicBundle_13_executeNutritionBalanceVerification.executeNutritionBalanceVerification;
/* AIVIC_FUNCTION_BUNDLE_END owner=executeNutritionBalanceVerification */

/* AIVIC_FUNCTION_BUNDLE_START owner=detectSlaExceedanceAndExecuteFallback exports=detectSlaExceedanceAndExecuteFallback */
const __aivicBundle_14_detectSlaExceedanceAndExecuteFallback = (() => {
  function detectSlaExceedanceAndExecuteFallback(input: {
    user_id: string;
    verification_start_time: Date;
    current_time: Date;
    sla_threshold_ms: number;
    product_data: Array<any>;
    shopping_list_id: string;
    family_members: Array<any>;
  }): {
    sla_exceeded: boolean;
    elapsed_time_ms: number;
    fallback_nutrition_verification_triggered: boolean;
    fallback_verification_status: string;
    fallback_verification_start_time: Date;
    fallback_verification_execution_mode: string;
    fallback_verification_result: {
      verification_completed: boolean;
      estimated_nutrition_balance: {
        estimated_avg_calories: number;
        estimated_avg_protein_g: number;
        estimated_avg_carbs_g: number;
        estimated_avg_fat_g: number;
        sample_size: number;
      };
    };
    next_step_handoff: {
      status: string;
      next_process_type: string;
      passed_nutrition_data: any;
      errors: Array<any>;
      process_continuation_allowed: boolean;
    };
    system_log_entries: Array<{
      event_type: string;
      timestamp: Date;
      severity: string;
      message: string;
    }>;
    fallback_execution_details: {
      original_sla_threshold_ms: number;
      actual_elapsed_ms: number;
      sla_overage_ms: number;
      fallback_mode: string;
      data_sampling_rate: number;
    };
    stakeholder_notification: {
      should_notify: boolean;
      notification_type: string;
      recipients: Array<string>;
    };
    process_flow_status: string;
    flow_interruption: boolean;
  } {
    const elapsedTimeMs = input.current_time.getTime() - input.verification_start_time.getTime();
    const slaExceeded = elapsedTimeMs > input.sla_threshold_ms;
    const slaOverageMs = Math.max(0, elapsedTimeMs - input.sla_threshold_ms);
  
    const systemLogEntries: Array<{
      event_type: string;
      timestamp: Date;
      severity: string;
      message: string;
    }> = [];
  
    if (slaExceeded) {
      systemLogEntries.push({
        event_type: "SLA_EXCEEDED",
        timestamp: input.current_time,
        severity: "WARNING",
        message: `SLA threshold of ${input.sla_threshold_ms}ms exceeded. Actual elapsed time: ${elapsedTimeMs}ms`,
      });
    }
  
    let fallbackTriggered = false;
    let fallbackVerificationStatus = "NOT_EXECUTED";
    let estimatedNutritionBalance = {
      estimated_avg_calories: 0,
      estimated_avg_protein_g: 0,
      estimated_avg_carbs_g: 0,
      estimated_avg_fat_g: 0,
      sample_size: 0,
    };
  
    if (slaExceeded) {
      fallbackTriggered = true;
      fallbackVerificationStatus = "EXECUTED";
  
      const productCount = input.product_data.length;
      estimatedNutritionBalance.sample_size = productCount;
  
      let totalCalories = 0;
      let totalProtein = 0;
      let totalCarbs = 0;
      let totalFat = 0;
  
      for (const product of input.product_data) {
        if (product.nutritional_value) {
          totalCalories += product.nutritional_value.calories || 0;
          totalProtein += product.nutritional_value.protein_g || 0;
          totalCarbs += product.nutritional_value.carbs_g || 0;
          totalFat += product.nutritional_value.fat_g || 0;
        }
      }
  
      if (productCount > 0) {
        estimatedNutritionBalance.estimated_avg_calories = totalCalories / productCount;
        estimatedNutritionBalance.estimated_avg_protein_g = totalProtein / productCount;
        estimatedNutritionBalance.estimated_avg_carbs_g = totalCarbs / productCount;
        estimatedNutritionBalance.estimated_avg_fat_g = totalFat / productCount;
      }
  
      systemLogEntries.push({
        event_type: "FALLBACK_VERIFICATION_EXECUTED",
        timestamp: input.current_time,
        severity: "INFO",
        message: `暫定的な栄養バランス検証を実行。商品データ ${productCount} 件を統計処理`,
      });
    }
  
    const passedNutritionData = {
      user_id: input.user_id,
      shopping_list_id: input.shopping_list_id,
      family_members: input.family_members,
      estimated_nutrition_balance: estimatedNutritionBalance,
      verification_timestamp: input.current_time,
      verification_mode: slaExceeded ? "SIMPLIFIED" : "STANDARD",
    };
  
    systemLogEntries.push({
      event_type: "NEXT_STEP_HANDOFF",
      timestamp: input.current_time,
      severity: "INFO",
      message: `次ステップ（在庫最適化処理）へのハンドオフを実行。栄養バランスデータを引き継ぎ`,
    });
  
    return {
      sla_exceeded: slaExceeded,
      elapsed_time_ms: elapsedTimeMs,
      fallback_nutrition_verification_triggered: fallbackTriggered,
      fallback_verification_status: fallbackVerificationStatus,
      fallback_verification_start_time: input.current_time,
      fallback_verification_execution_mode: "SIMPLIFIED",
      fallback_verification_result: {
        verification_completed: fallbackTriggered,
        estimated_nutrition_balance: estimatedNutritionBalance,
      },
      next_step_handoff: {
        status: "READY_FOR_NEXT_STEP",
        next_process_type: "INVENTORY_OPTIMIZATION",
        passed_nutrition_data: passedNutritionData,
        errors: [],
        process_continuation_allowed: true,
      },
      system_log_entries: systemLogEntries,
      fallback_execution_details: {
        original_sla_threshold_ms: input.sla_threshold_ms,
        actual_elapsed_ms: elapsedTimeMs,
        sla_overage_ms: slaOverageMs,
        fallback_mode: "SIMPLIFIED",
        data_sampling_rate: 1.0,
      },
      stakeholder_notification: {
        should_notify: slaExceeded,
        notification_type: "SLA_DELAY_DETECTED",
        recipients: ["product_manager", "development_team"],
      },
      process_flow_status: slaExceeded ? "CONTINUING_WITH_FALLBACK" : "NORMAL",
      flow_interruption: false,
    };
  }
  return { detectSlaExceedanceAndExecuteFallback };
})();
export const detectSlaExceedanceAndExecuteFallback = __aivicBundle_14_detectSlaExceedanceAndExecuteFallback.detectSlaExceedanceAndExecuteFallback;
/* AIVIC_FUNCTION_BUNDLE_END owner=detectSlaExceedanceAndExecuteFallback */

/* AIVIC_FUNCTION_BUNDLE_START owner=detectSlaDelayAndExecuteFallback exports=detectSlaDelayAndExecuteFallback */
const __aivicBundle_15_detectSlaDelayAndExecuteFallback = (() => {
  function detectSlaDelayAndExecuteFallback(input: {
    processStartTime: Date;
    currentCheckTime: Date;
    slaThresholdMs: number;
    logger?: { logs: string[] };
    fallbackExecutor?: (params: { delayMs: number; triggeredAt: Date }) => void;
  }): { isDelayed: boolean; elapsedMs: number; message: string } {
    const elapsedMs = input.currentCheckTime.getTime() - input.processStartTime.getTime();
    const isDelayed = elapsedMs >= input.slaThresholdMs;
  
    const message = isDelayed ? "遅延あり" : "遅延なし";
  
    if (isDelayed && input.fallbackExecutor) {
      const delayMs = elapsedMs - input.slaThresholdMs;
      input.fallbackExecutor({
        delayMs,
        triggeredAt: input.currentCheckTime,
      });
  
      if (input.logger) {
        input.logger.logs.push(
          `[${input.currentCheckTime.toISOString()}] SLA遅延検出: 経過時間=${elapsedMs}ms, 閾値=${input.slaThresholdMs}ms, 超過=${delayMs}ms`
        );
        input.logger.logs.push(
          `[${input.currentCheckTime.toISOString()}] 代替処理を実行しました`
        );
      }
    }
  
    return {
      isDelayed,
      elapsedMs,
      message,
    };
  }
  return { detectSlaDelayAndExecuteFallback };
})();
export const detectSlaDelayAndExecuteFallback = __aivicBundle_15_detectSlaDelayAndExecuteFallback.detectSlaDelayAndExecuteFallback;
/* AIVIC_FUNCTION_BUNDLE_END owner=detectSlaDelayAndExecuteFallback */

/* AIVIC_FUNCTION_BUNDLE_START owner=detectSLADelayAndExecuteAlternativeProcess exports=detectSLADelayAndExecuteAlternativeProcess */
const __aivicBundle_16_detectSLADelayAndExecuteAlternativeProcess = (() => {
  function detectSLADelayAndExecuteAlternativeProcess(
    user_id: string,
    analysis_period: string,
    elapsed_time_hours: string | number | null | undefined,
    sla_threshold_hours: number | null | undefined
  ): { is_sla_exceeded: boolean; elapsed_time_hours: number; sla_threshold_hours: number; alternative_process_triggered: boolean; status: string } {
    // Validate user_id
    if (typeof user_id !== "string" || user_id.trim() === "") {
      throw new Error("ユーザーIDが無効です");
    }
  
    // Validate analysis_period (ISO 8601 format check)
    if (typeof analysis_period !== "string" || analysis_period.trim() === "") {
      throw new Error("分析期間が無効です");
    }
    const periodDate = new Date(analysis_period);
    if (isNaN(periodDate.getTime())) {
      throw new Error("分析期間が無効な日時フォーマットです");
    }
  
    // Validate elapsed_time_hours
    if (
      elapsed_time_hours === null ||
      elapsed_time_hours === undefined ||
      typeof elapsed_time_hours === "string"
    ) {
      throw new Error("経過時間が無効です");
    }
    const elapsedNum = Number(elapsed_time_hours);
    if (isNaN(elapsedNum) || !isFinite(elapsedNum) || elapsedNum < 0) {
      throw new Error("経過時間が無効です");
    }
  
    // Validate sla_threshold_hours
    if (
      sla_threshold_hours === null ||
      sla_threshold_hours === undefined
    ) {
      throw new Error("SLA閾値が無効です");
    }
    const thresholdNum = Number(sla_threshold_hours);
    if (isNaN(thresholdNum) || !isFinite(thresholdNum) || thresholdNum < 0) {
      throw new Error("SLA閾値が無効です");
    }
  
    // Determine if SLA is exceeded
    const is_sla_exceeded = elapsedNum > thresholdNum;
    const alternative_process_triggered = is_sla_exceeded;
    const status = is_sla_exceeded ? "sla_exceeded_with_alternative" : "normal";
  
    return {
      is_sla_exceeded,
      elapsed_time_hours: elapsedNum,
      sla_threshold_hours: thresholdNum,
      alternative_process_triggered,
      status,
    };
  }
  return { detectSLADelayAndExecuteAlternativeProcess };
})();
export const detectSLADelayAndExecuteAlternativeProcess: (...args: any[]) => any = (...args: any[]) => (__aivicBundle_16_detectSLADelayAndExecuteAlternativeProcess.detectSLADelayAndExecuteAlternativeProcess as (...args: any[]) => any)(...args);
/* AIVIC_FUNCTION_BUNDLE_END owner=detectSLADelayAndExecuteAlternativeProcess */

/* AIVIC_FUNCTION_BUNDLE_START owner=determineMonthlyVerificationTiming exports=determineMonthlyVerificationTiming */
const __aivicBundle_17_determineMonthlyVerificationTiming = (() => {
  interface DetermineMonthlyVerificationTimingInput {
    previous_month_forecast_data_exists?: boolean;
    previous_month_actual_demand_data_exists?: boolean;
    currentMonthYear?: string;
    accessDate?: Date;
    verification_trigger_date?: Date;
    previous_month_data?: any;
    completeness_threshold_percentage?: number;
  }
  
  interface DailyDataRecord {
    date: string;
    sales?: number;
  }
  
  function calculateDataCompleteness(
    monthlyData: any,
    threshold: number
  ): {
    isComplete: boolean;
    completenessPercentage: number;
    missingCount: number;
    missingRanges: Array<{ start_date: string; end_date: string; reason: string }>;
  } {
    if (!monthlyData || !monthlyData.daily_sales_data) {
      return {
        isComplete: false,
        completenessPercentage: 0,
        missingCount: monthlyData?.total_sales_expected_count || 0,
        missingRanges: [],
      };
    }
  
    const dailyData = monthlyData.daily_sales_data as DailyDataRecord[];
    const expectedCount = monthlyData.total_sales_expected_count || 31;
    const actualCount = dailyData.length;
  
    const missingRanges: Array<{ start_date: string; end_date: string; reason: string }> = [];
    const presentDates = new Set(dailyData.map((d) => d.date));
  
    // Detect null values
    dailyData.forEach((record) => {
      if (record.sales === null) {
        missingRanges.push({
          start_date: record.date,
          end_date: record.date,
          reason: "null_value",
        });
      }
    });
  
    // Detect absent records (gaps in sequence)
    const year = monthlyData.year;
    const month = monthlyData.month;
    const daysInMonth = new Date(year, month, 0).getDate();
  
    let rangeStart: string | null = null;
    for (let day = 1; day <= daysInMonth; day++) {
      const dateStr = `${year}-${String(month).padStart(2, "0")}-${String(day).padStart(2, "0")}`;
      if (!presentDates.has(dateStr)) {
        if (!rangeStart) {
          rangeStart = dateStr;
        }
      } else {
        if (rangeStart) {
          const prevDay = day - 1;
          const prevDateStr = `${year}-${String(month).padStart(2, "0")}-${String(prevDay).padStart(2, "0")}`;
          missingRanges.push({
            start_date: rangeStart,
            end_date: prevDateStr,
            reason: "absent_record",
          });
          rangeStart = null;
        }
      }
    }
    if (rangeStart) {
      const lastDateStr = `${year}-${String(month).padStart(2, "0")}-${String(daysInMonth).padStart(2, "0")}`;
      missingRanges.push({
        start_date: rangeStart,
        end_date: lastDateStr,
        reason: "absent_record",
      });
    }
  
    const completenessPercentage = Math.round((actualCount / expectedCount) * 100);
    const isComplete = completenessPercentage >= threshold;
    const missingCount = expectedCount - actualCount;
  
    return {
      isComplete,
      completenessPercentage,
      missingCount,
      missingRanges,
    };
  }
  
  function getPreviousMonth(date: Date): { year: number; month: number; monthStr: string } {
    const d = new Date(date);
    d.setMonth(d.getMonth() - 1);
    const year = d.getFullYear();
    const month = d.getMonth() + 1;
    const monthStr = `${year}-${String(month).padStart(2, "0")}`;
    return { year, month, monthStr };
  }
  
  function getNextMonth(date: Date): { year: number; month: number; monthStr: string } {
    const d = new Date(date);
    d.setMonth(d.getMonth() + 1);
    const year = d.getFullYear();
    const month = d.getMonth() + 1;
    const monthStr = `${year}-${String(month).padStart(2, "0")}`;
    return { year, month, monthStr };
  }
  
   function determineMonthlyVerificationTiming(
    currentDateOrInput: Date | DetermineMonthlyVerificationTimingInput,
    optionsOrUndefined?: DetermineMonthlyVerificationTimingInput
  ): MonthlyVerificationTimingResult | boolean {
    let currentDate: Date;
    let options: DetermineMonthlyVerificationTimingInput;
  
    // Handle overloaded signatures
    if (currentDateOrInput instanceof Date) {
      currentDate = currentDateOrInput;
      options = optionsOrUndefined || {};
    } else {
      // First argument is an object
      options = currentDateOrInput;
      currentDate = options.accessDate || options.verification_trigger_date || new Date();
    }
  
    const dayOfMonth = currentDate.getDate();
    const currentYear = currentDate.getFullYear();
    const currentMonth = currentDate.getMonth() + 1;
    const currentMonthStr = `${currentYear}-${String(currentMonth).padStart(2, "0")}`;
    const judgmentDatetime = currentDate.toISOString();
  
    // Case 1: Simple boolean return (when only Date and basic options provided)
    if (
      currentDateOrInput instanceof Date &&
      (options.previous_month_forecast_data_exists !== undefined ||
        options.previous_month_actual_demand_data_exists !== undefined)
    ) {
      const forecastExists = options.previous_month_forecast_data_exists ?? false;
      const actualExists = options.previous_month_actual_demand_data_exists ?? false;
  
      if (dayOfMonth >= 1 && dayOfMonth <= 5) {
        return forecastExists && actualExists;
      } else {
        return false;
      }
    }
  
    // Case 2: Object input with accessDate and currentMonthYear (SCEN-256 style)
    if (options.accessDate && options.currentMonthYear) {
      const accessDay = options.accessDate.getDate();
      const nextMonth = getNextMonth(options.accessDate);
      const nextMonthDateStr = `${nextMonth.year}-${String(nextMonth.month).padStart(2, "0")}-01`;
  
      if (accessDay >= 6) {
        return {
          shouldExecuteVerification: false,
          verificationStatus: "skipped",
          notificationMessage: `検証実行は翌月に予定されています。次回検証予定日: ${nextMonthDateStr}`,
          nextScheduledVerificationDate: nextMonthDateStr,
        } as any;
      }
    }
  
    // Case 3: Date input without options (SCEN-257 style)
    if (currentDateOrInput instanceof Date && !optionsOrUndefined) {
      const prevMonth = getPreviousMonth(currentDate);
      const verifiedMonthStr = `${prevMonth.year}-${String(prevMonth.month).padStart(2, "0")}`;
  
      if (dayOfMonth >= 1 && dayOfMonth <= 5) {
        return {
          should_execute_verification: true,
          verification_status: "verification_ready",
          next_action: "start_verification",
          verified_month: verifiedMonthStr,
          judgment_datetime: judgmentDatetime,
        } as any;
      } else {
        return {
          should_execute_verification: false,
          verification_status: "verification_wait",
          next_action: "wait_next_month",
          verified_month: verifiedMonthStr,
          judgment_datetime: judgmentDatetime,
        } as any;
      }
    }
  
    // Case 4: Object input with previous_month_data (SCEN-258 style - incomplete data check)
    if (options.previous_month_data && options.verification_trigger_date) {
      const triggerDate = options.verification_trigger_date;
      const threshold = options.completeness_threshold_percentage || 95;
      const monthlyData = options.previous_month_data;
  
      const completeness = calculateDataCompleteness(monthlyData, threshold);
  
      if (!completeness.isComplete) {
        const prevMonth = getPreviousMonth(triggerDate);
        const prevMonthStr = `${prevMonth.year}年${String(prevMonth.month).padStart(2, "0")}月`;
  
        const notificationDetails = {
          message: `検証実行不可: 前月データが不完全です`,
          missing_data_count: completeness.missingCount,
          data_completeness_percentage: completeness.completenessPercentage,
          required_threshold_percentage: threshold,
          missing_date_ranges: completeness.missingRanges,
        };
  
        const notificationRequest = {
          notification_type: "verification_cannot_proceed",
          user_id: "system_admin",
          content: {
            title: "月次検証が実行できません",
            body: `前月のデータが不完全です。${prevMonthStr}のデータ完全性: ${completeness.completenessPercentage}%（必要: ${threshold}%）`,
          },
        };
  
        return {
          status: "error",
          processing_mode: "error_handling",
          fallback_executed: false,
          system_log: `Data completeness check failed: ${completeness.completenessPercentage}% < ${threshold}%`,
          validation_result: {
            protein_grams: 0,
            carbohydrates_grams: 0,
            fat_grams: 0,
            is_provisional: false,
            fallback_source: "none",
          },
          error_code: "INCOMPLETE_PREVIOUS_MONTH_DATA",
          error_message: `データ不完全エラー: ${prevMonthStr}のデータ完全性が${threshold}%以上必要です（現在: ${completeness.completenessPercentage}%）`,
          notification_details: notificationDetails,
          should_proceed_with_verification: false,
          verification_skipped: true,
          skip_reason: "前月データの不完全性により検証実行不可",
          notification_request: notificationRequest,
          log_timestamp: new Date(),
          detection_timestamp: triggerDate,
          fallback_completion_timestamp: new Date(),
        } as any;
      }
    }
  
    // Default fallback
    return {
      should_execute_verification: false,
      verification_status: "verification_wait",
      next_action: "wait_next_month",
      verified_month: currentMonthStr,
      judgment_datetime: judgmentDatetime,
    } as any;
  }
  return { determineMonthlyVerificationTiming };
})();
export const determineMonthlyVerificationTiming: (...args: any[]) => any = (...args: any[]) => (__aivicBundle_17_determineMonthlyVerificationTiming.determineMonthlyVerificationTiming as (...args: any[]) => any)(...args);
/* AIVIC_FUNCTION_BUNDLE_END owner=determineMonthlyVerificationTiming */

/* AIVIC_FUNCTION_BUNDLE_START owner=identifyDemandForecastAccuracyDecline exports=identifyDemandForecastAccuracyDecline */
const __aivicBundle_18_identifyDemandForecastAccuracyDecline = (() => {
  function identifyDemandForecastAccuracyDecline(input: {
    previous_month_accuracy: number;
    current_month_accuracy: number;
    forecast_data: Array<{
      forecast_id: string;
      product_code: string;
      forecast_quantity: number;
      actual_quantity: number;
      forecast_date: string;
    }>;
    external_factors: Array<{
      factor_type: string;
      impact_level: string;
      confidence_score: number;
    }>;
  }): AccuracyDeclineResult {
    const accuracyDeclinePercentage =
      input.previous_month_accuracy - input.current_month_accuracy;
    const declineThreshold = 10;
    const declineThresholdExceeded = accuracyDeclinePercentage >= declineThreshold;
    const accuracyDeclineDetected = declineThresholdExceeded;
  
    // Calculate forecast error metrics from forecast_data
    const forecastErrors = input.forecast_data.map((forecast) => {
      const absoluteError = Math.abs(
        forecast.forecast_quantity - forecast.actual_quantity,
      );
      const percentageError =
        forecast.forecast_quantity > 0
          ? (absoluteError / forecast.forecast_quantity) * 100
          : 0;
      return {
        forecast_id: forecast.forecast_id,
        product_code: forecast.product_code,
        absolute_error: absoluteError,
        percentage_error: percentageError,
      };
    });
  
    const avgForecastError =
      forecastErrors.length > 0
        ? forecastErrors.reduce((sum, e) => sum + e.percentage_error, 0) /
          forecastErrors.length
        : 0;
  
    const maxForecastError =
      forecastErrors.length > 0
        ? Math.max(...forecastErrors.map((e) => e.percentage_error))
        : 0;
  
    // Build root cause hypotheses from external_factors
    const rootCauseHypotheses = input.external_factors
      .map((factor, index) => {
        // Calculate impact_score based on impact_level and confidence_score
        const impactLevelMultiplier =
          factor.impact_level === "high"
            ? 0.9
            : factor.impact_level === "medium"
              ? 0.6
              : 0.3;
        const impactScore = Math.round(
          factor.confidence_score * impactLevelMultiplier,
        );
  
        // Generate supporting metrics based on forecast data
        const supportingMetrics = [
          {
            metric_name: "average_forecast_error_percentage",
            metric_value: Math.round(avgForecastError * 100) / 100,
          },
          {
            metric_name: "max_forecast_error_percentage",
            metric_value: Math.round(maxForecastError * 100) / 100,
          },
          {
            metric_name: "confidence_score",
            metric_value: factor.confidence_score,
          },
          {
            metric_name: "affected_forecast_count",
            metric_value: forecastErrors.length,
          },
        ];
  
        // Generate description based on factor type
        const descriptionMap: Record<string, string> = {
          weather_pattern:
            "Weather pattern changes have significantly impacted demand forecasting accuracy, affecting seasonal and short-term demand predictions.",
          demand_pattern_shift:
            "Consumer demand patterns have shifted unexpectedly, causing the forecast model to underestimate or overestimate actual quantities.",
          competitor_campaign:
            "Competitor marketing campaigns have influenced market dynamics, reducing forecast accuracy for affected product categories.",
          data_quality_issue:
            "Data quality issues in historical records or real-time data collection have degraded the training dataset reliability.",
          model_drift:
            "The forecast model has experienced drift due to changing market conditions, requiring retraining or recalibration.",
        };
  
        const description =
          descriptionMap[factor.factor_type] ||
          `${factor.factor_type} has contributed to accuracy decline with confidence level ${factor.confidence_score}%.`;
  
        return {
          priority: 0, // Will be assigned after sorting
          factor_type: factor.factor_type,
          impact_score: impactScore,
          confidence_score: factor.confidence_score,
          supporting_metrics: supportingMetrics,
          description: description,
        };
      })
      .sort((a, b) => b.impact_score - a.impact_score)
      .map((hypothesis, index) => ({
        ...hypothesis,
        priority: index + 1,
      }));
  
    const analysisTimestamp = new Date().toISOString();
  
    return {
      accuracy_decline_detected: accuracyDeclineDetected,
      accuracy_decline_percentage: accuracyDeclinePercentage,
      decline_threshold_exceeded: declineThresholdExceeded,
      root_cause_hypotheses: rootCauseHypotheses,
      previous_month_accuracy: input.previous_month_accuracy,
      current_month_accuracy: input.current_month_accuracy,
      analysis_timestamp: analysisTimestamp,
    };
  }
  return { identifyDemandForecastAccuracyDecline };
})();
export const identifyDemandForecastAccuracyDecline = __aivicBundle_18_identifyDemandForecastAccuracyDecline.identifyDemandForecastAccuracyDecline;
/* AIVIC_FUNCTION_BUNDLE_END owner=identifyDemandForecastAccuracyDecline */

/* AIVIC_FUNCTION_BUNDLE_START owner=extractPrecisionDeclineFactor exports=extractPrecisionDeclineFactor */
const __aivicBundle_19_extractPrecisionDeclineFactor = (() => {
  function extractPrecisionDeclineFactor(input: {
    forecast_categories: Array<{
      category_id: number;
      category_name: string;
      predicted_demand: number;
      actual_demand: number;
      divergence_rate: number;
      month: string;
    }>;
    threshold: number;
    analysis_period: string;
  }): PrecisionDeclineFactorResult {
    const detectionTimestamp = new Date().toISOString();
  
    const detectedCategories: Array<{
      category_id: number;
      category_name: string;
      divergence_rate: number;
      threshold_exceeded_by: number;
      status: string;
    }> = [];
  
    const excludedCategories: Array<{
      category_id: number;
      category_name: string;
      divergence_rate: number;
      status: string;
    }> = [];
  
    const primaryFactorsMap: Map<
      number,
      {
        category_id: number;
        category_name: string;
        factors: Array<{
          factor_type: string;
          factor_description: string;
          impact_score: number;
          priority: number;
        }>;
      }
    > = new Map();
  
    for (const category of input.forecast_categories) {
      if (category.divergence_rate > input.threshold) {
        const thresholdExceededBy = category.divergence_rate - input.threshold;
        detectedCategories.push({
          category_id: category.category_id,
          category_name: category.category_name,
          divergence_rate: category.divergence_rate,
          threshold_exceeded_by: thresholdExceededBy,
          status: "precision_declined",
        });
  
        const factors = extractFactorsForCategory(
          category.divergence_rate,
          input.threshold
        );
        primaryFactorsMap.set(category.category_id, {
          category_id: category.category_id,
          category_name: category.category_name,
          factors,
        });
      } else {
        excludedCategories.push({
          category_id: category.category_id,
          category_name: category.category_name,
          divergence_rate: category.divergence_rate,
          status: "normal",
        });
      }
    }
  
    const primaryFactors = Array.from(primaryFactorsMap.values());
  
    const summary = {
      total_categories: input.forecast_categories.length,
      declined_categories_count: detectedCategories.length,
      normal_categories_count: excludedCategories.length,
      overall_status:
        detectedCategories.length > 0
          ? "precision_decline_detected"
          : "normal",
    };
  
    const logRecord = {
      event_type: "precision_decline_detected",
      detected_categories_count: detectedCategories.length,
      analysis_period: input.analysis_period,
      threshold_value: input.threshold,
      detected_at: detectionTimestamp,
      analysis_status: "completed",
    };
  
    return {
      detected_categories: detectedCategories,
      excluded_categories: excludedCategories,
      primary_factors: primaryFactors,
      detection_timestamp: detectionTimestamp,
      log_record: logRecord,
      summary,
    };
  }
  
  function extractFactorsForCategory(
    divergenceRate: number,
    threshold: number
  ): Array<{
    factor_type: string;
    factor_description: string;
    impact_score: number;
    priority: number;
  }> {
    const excessDivergence = divergenceRate - threshold;
  
    const baseFactors = [
      {
        factor_type: "seasonal_trend",
        factor_description: "季節トレンドの変化",
        impact_score: 0.35 + excessDivergence * 0.5,
        priority: 1,
      },
      {
        factor_type: "supply_chain_delay",
        factor_description: "供給チェーン遅延",
        impact_score: 0.25 + excessDivergence * 0.3,
        priority: 2,
      },
      {
        factor_type: "external_event",
        factor_description: "外部イベント影響",
        impact_score: 0.2 + excessDivergence * 0.2,
        priority: 3,
      },
      {
        factor_type: "model_parameter_drift",
        factor_description: "モデルパラメータドリフト",
        impact_score: 0.2 + excessDivergence * 0.15,
        priority: 4,
      },
    ];
  
    return baseFactors.map((factor) => ({
      ...factor,
      impact_score: Math.min(1.0, Math.max(0.0, factor.impact_score)),
    }));
  }
  return { extractPrecisionDeclineFactor };
})();
export const extractPrecisionDeclineFactor = __aivicBundle_19_extractPrecisionDeclineFactor.extractPrecisionDeclineFactor;
/* AIVIC_FUNCTION_BUNDLE_END owner=extractPrecisionDeclineFactor */

/* AIVIC_FUNCTION_BUNDLE_START owner=detectAccuracyDeclineAndExtractMainFactors exports=detectAccuracyDeclineAndExtractMainFactors */
const __aivicBundle_20_detectAccuracyDeclineAndExtractMainFactors = (() => {
  function detectAccuracyDeclineAndExtractMainFactors(input: {
    previous_month_accuracy: number;
    current_month_accuracy: number;
  }): AccuracyDeclineCheckResult {
    const declinePercentage = input.previous_month_accuracy - input.current_month_accuracy;
    const accuracyDeclined = declinePercentage >= 10;
  
    if (!accuracyDeclined) {
      return {
        accuracy_declined: false,
        main_factors_extracted: false,
        main_factors: [],
        extraction_log_entry_created: false,
        system_error_occurred: false,
      };
    }
  
    const mainFactors = extractMainFactorsInternal(
      input.previous_month_accuracy,
      input.current_month_accuracy,
      declinePercentage
    );
  
    const extractionLogCreated = createExtractionLogEntry(
      input.previous_month_accuracy,
      input.current_month_accuracy,
      mainFactors
    );
  
    return {
      accuracy_declined: true,
      main_factors_extracted: true,
      main_factors: mainFactors,
      extraction_log_entry_created: extractionLogCreated,
      system_error_occurred: false,
    };
  }
  
  function extractMainFactorsInternal(
    previousAccuracy: number,
    currentAccuracy: number,
    declinePercentage: number
  ): Array<any> {
    const factors: Array<any> = [];
  
    if (declinePercentage >= 10 && declinePercentage < 20) {
      factors.push({
        factor_type: "moderate_decline",
        factor_description: "Moderate accuracy decline detected",
        impact_score: declinePercentage,
        priority: 2,
      });
    } else if (declinePercentage >= 20) {
      factors.push({
        factor_type: "severe_decline",
        factor_description: "Severe accuracy decline detected",
        impact_score: declinePercentage,
        priority: 1,
      });
    }
  
    return factors;
  }
  
  function createExtractionLogEntry(
    previousAccuracy: number,
    currentAccuracy: number,
    mainFactors: Array<any>
  ): boolean {
    if (mainFactors.length === 0) {
      return false;
    }
  
    return true;
  }
  return { detectAccuracyDeclineAndExtractMainFactors };
})();
export const detectAccuracyDeclineAndExtractMainFactors = __aivicBundle_20_detectAccuracyDeclineAndExtractMainFactors.detectAccuracyDeclineAndExtractMainFactors;
/* AIVIC_FUNCTION_BUNDLE_END owner=detectAccuracyDeclineAndExtractMainFactors */

/* AIVIC_FUNCTION_BUNDLE_START owner=extractDemandForecastAnomalies exports=extractDemandForecastAnomalies */
const __aivicBundle_21_extractDemandForecastAnomalies = (() => {
  function extractDemandForecastAnomalies(
    data: Array<{
      period_id: string;
      product_id: string;
      forecast_value: number | string;
      actual_value: number;
      divergence: number;
      divergence_rate: number | null;
      category: string;
      external_factors: Array<string>;
      timestamp: string;
    }>
  ): Array<DemandForecastAnomalyResult> {
    const results: Array<DemandForecastAnomalyResult> = [];
  
    for (const record of data) {
      // Validate period_id
      if (record.period_id === undefined || record.period_id === null) {
        throw new Error("期間IDが不完全です");
      }
      if (typeof record.period_id !== "string" || record.period_id.trim() === "") {
        throw new Error("期間IDが不完全です");
      }
  
      // Validate product_id
      if (record.product_id === undefined || record.product_id === null) {
        throw new Error("商品IDが不完全です");
      }
      if (typeof record.product_id !== "string" || record.product_id.trim() === "") {
        throw new Error("商品IDが不完全です");
      }
  
      // Validate forecast_value
      if (record.forecast_value === undefined || record.forecast_value === null) {
        throw new Error("予測値が不完全です");
      }
      if (typeof record.forecast_value !== "number") {
        throw new Error("予測値が不完全です");
      }
  
      // Validate actual_value
      if (record.actual_value === undefined || record.actual_value === null) {
        throw new Error("実績値が不完全です");
      }
      if (typeof record.actual_value !== "number") {
        throw new Error("実績値が不完全です");
      }
      if (record.actual_value < 0) {
        throw new Error("実績値が不完全です");
      }
  
      // Validate divergence
      if (record.divergence === undefined || record.divergence === null) {
        throw new Error("乖離度が不完全です");
      }
      if (typeof record.divergence !== "number") {
        throw new Error("乖離度が不完全です");
      }
  
      // Validate divergence_rate
      if (record.divergence_rate === undefined || record.divergence_rate === null) {
        throw new Error("乖離度が不完全です");
      }
      if (typeof record.divergence_rate !== "number") {
        throw new Error("乖離度が不完全です");
      }
  
      // Validate category
      if (record.category === undefined || record.category === null) {
        throw new Error("カテゴリが不完全です");
      }
      if (typeof record.category !== "string" || record.category.trim() === "") {
        throw new Error("カテゴリが不完全です");
      }
  
      // Validate timestamp
      if (record.timestamp === undefined || record.timestamp === null) {
        throw new Error("タイムスタンプが不完全です");
      }
      if (typeof record.timestamp !== "string") {
        throw new Error("タイムスタンプが不完全です");
      }
      const parsedDate = new Date(record.timestamp);
      if (isNaN(parsedDate.getTime())) {
        throw new Error("タイムスタンプが不完全です");
      }
  
      // Validate external_factors
      if (record.external_factors === undefined || record.external_factors === null) {
        throw new Error("外部要因が不完全です");
      }
      if (!Array.isArray(record.external_factors)) {
        throw new Error("外部要因が不完全です");
      }
  
      // Determine if anomaly (divergence_rate >= 0.10)
      const isAnomaly = record.divergence_rate >= 0.10;
  
      // Extract primary factors from external_factors
      const primaryFactors = record.external_factors.map((factor) => ({
        factor_name: factor,
        impact_level: "medium",
      }));
  
      const anomalyResult: DemandForecastAnomalyResult = {
        anomaly_id: randomUUID(),
        detected_at: new Date().toISOString(),
        divergence_rate: record.divergence_rate,
        primary_factors: primaryFactors,
        is_anomaly: isAnomaly,
      };
  
      results.push(anomalyResult);
    }
  
    return results;
  }
  return { extractDemandForecastAnomalies };
})();
export const extractDemandForecastAnomalies = __aivicBundle_21_extractDemandForecastAnomalies.extractDemandForecastAnomalies;
/* AIVIC_FUNCTION_BUNDLE_END owner=extractDemandForecastAnomalies */
