// AUTO-GENERATED by AIVIC logic-scaffolder (3-stage per-function gen)
// slug: it-1
// 関数: analyzeSegmentDifferentiationEffect, analyzeSegmentStatisticalReliability, analyzeFeatureUsagePattern, analyzeFeatureUsagePatterns, classifyPainFactors, analyzeMenuGenerationFlowForPainFactors, generatePainMatrixByPriority, analyzeNutrientIntake, analyzeNutritionAchievementRate, calculateNutritionAchievementByAgeGroup

export interface SegmentMetrics {
    week: string;
    mealGenerationSuccessRate: number;
    cookingTimeShorteningDegree: number;
    satisfactionScore: number;
}
export interface SegmentAnalysisInput {
    segmentId: string;
    segmentName: string;
    userCount: number;
    analysisStartDate: Date;
    analysisEndDate: Date;
    weeklyMetricsData: SegmentMetrics[];
    previousWeeklyMetricsData?: SegmentMetrics[];
}
export interface SegmentAnalysisResult {
    segmentId: string;
    segmentName: string;
    userCount: number;
    averageMealGenerationSuccessRate: number;
    averageCookingTimeShorteningDegree: number;
    averageSatisfactionScore: number;
    mealGenerationSuccessRateMin: number;
    mealGenerationSuccessRateMax: number;
    cookingTimeShorteningDegreeMin: number;
    cookingTimeShorteningDegreeMax: number;
    satisfactionScoreMin: number;
    satisfactionScoreMax: number;
    weeklyTrends: SegmentMetrics[];
    exportFormat: {
        format: string;
        fileName: string;
    };
    exportData: string;
    unitLabels: {
        mealGenerationSuccessRate: string;
        cookingTimeShorteningDegree: string;
        satisfactionScore: string;
    };
    analysisStartDate: string;
    analysisEndDate: string;
    graphDatasets: Array<{
        label: string;
        dataPoints: number[];
    }>;
    comparisonMetrics?: {
        mealGenerationSuccessRateChange: number;
    };
}
export interface ReliabilityAnalysisInput {
    segmentId: string;
    segmentName: string;
    samples: Array<{
        userId: string;
        foodExpense: number;
        nutritionScore: number;
        satisfactionScore: number;
    }>;
}
export interface ReliabilityAnalysisResult {
    segmentId: string;
    sampleSize: number;
    reliabilityLevel: string;
    confidenceScore: number;
    warningMessage: string;
    canUseForAnalysis: boolean;
}
export interface FeatureUsageLog {
    log_id: string;
    user_id: string;
    feature_name: string;
    action_type: string;
    step_sequence: number;
    timestamp: Date;
}
export interface CompetitiveFeatureDefinition {
    feature_id: string;
    feature_name: string;
    is_proprietary: boolean;
    competitive_advantage_score: number;
    unique_capability_description: string;
}
export interface FeatureUsageAnalysisInput {
    user_id: string;
    period_start: Date;
    period_end: Date;
    user_segment: string;
    usage_logs: FeatureUsageLog[];
    competitive_feature_definitions: CompetitiveFeatureDefinition[];
}
export interface FeatureUsageFrequencyRecord {
    feature_name: string;
    access_count: number;
    total_sessions: number;
    completion_count: number;
    usage_rate_percent: number;
}
export interface FeatureAbandonmentRecord {
    feature_name: string;
    abandonment_count: number;
    abandonment_rate_percent: number;
    abandonment_step_distribution: Record<string, number>;
}
export interface CompetitiveDifferentiationRecord {
    feature_name: string;
    is_proprietary: boolean;
    competitive_advantage_score: number;
    usage_frequency_rank: number;
    user_completion_rate_percent: number;
    satisfaction_indicator: string;
}
export interface FeatureUsageAnalysisResult {
    feature_usage_frequency: FeatureUsageFrequencyRecord[];
    feature_abandonment_analysis: FeatureAbandonmentRecord[];
    competitive_differentiation_basis: {
        proprietary_features_analysis: CompetitiveDifferentiationRecord[];
    };
    analysis_metadata: {
        analysis_period_start: Date;
        analysis_period_end: Date;
        total_logs_processed: number;
        total_sessions_analyzed: number;
        unique_features_tracked: number;
    };
    exportable_report_data: {
        report_generated_timestamp: string;
        usage_frequency_table: any[];
        abandonment_analysis_table: any[];
        competitive_analysis_table: any[];
    };
    filterable_dimensions: string[];
}
export interface PainFactorClassificationInput {
    exit_point: string;
    constraint_pattern: string;
    user_id: string;
    family_id: string;
    timestamp: Date;
    input_value: any;
    field_name: string;
}
export interface PainFactorClassificationResult {
    exit_point: string;
    constraint_pattern: string;
    pain_factor_category: string;
    priority: number;
    classification_timestamp: Date;
}
export interface MenuGenerationFlowAnalysisInput {
    user_id: string;
    menu_generation_flow_history: any[];
}
export interface WithdrawalReason {
    withdrawal_reason_id: string;
    reason_text: string;
    priority_level: number;
    importance_score: number;
    registration_order: number;
}
export interface PainMatrixCell {
    cell_id: string;
    priority_level: number;
    importance_score: number;
    withdrawal_reason_id: string;
    reason_text: string;
    row_index: number;
    column_index: number;
    sort_order: number;
}
export interface PainMatrixResult {
    matrix_id: string;
    total_rows: number;
    total_columns: number;
    cells: PainMatrixCell[];
    generated_at: string;
}
export interface FamilyMember {
    member_id: string;
    name: string;
    age: number;
    gender: string;
}
export interface MealRecord {
    meal_date: string;
    member_id: string;
    calories: number;
    protein: number;
    fat: number;
    carbohydrates: number;
    vitamin_a: number;
    calcium: number;
}
export interface NutritionIntakeAnalysisInput {
    family_members: FamilyMember[];
    meal_records: MealRecord[];
    analysis_date: string;
}
export interface NutritionStandard {
  [key: string]: any;
}
export interface ComplianceStatus {
    status: string;
    percentage: number;
    is_compliant: boolean;
}
export interface NutritionIntakeAnalysisResult {
    nutrition_standards: Record<string, NutritionStandard>;
    actual_intake: Record<string, NutritionStandard>;
    achievement_rates: Record<string, Record<string, number>>;
    compliance: Record<string, Record<string, ComplianceStatus>>;
    analysis_timestamp: string;
}
export interface NutritionAchievementRateInput {
    user_id: string;
    target_date: Date;
    nutrition_logs: Array<{
        nutrient_name: string;
        intake_amount: number;
        unit: string;
        logged_at: Date;
    }>;
    nutrition_standards: Array<{
        nutrient_name: string;
        daily_target: number;
        unit: string;
    }>;
}
export interface NutritionAchievementRateResult {
    has_nutrition_logs: boolean;
    achievement_rates: Array<{
        nutrient_name: string;
        achievement_rate: number;
    }>;
    is_dashboard_renderable: boolean;
    error_message: string;
}
export interface AgeGroupNutritionInput {
    member_id: string;
    age: number;
    nutrition_standard: {
        calories: number;
        protein: number;
    };
    nutrition_actual: {
        calories: number;
        protein: number;
    };
    achievement_score: {
        calories: number;
        protein: number;
    };
}


import { randomUUID } from "crypto";

/* AIVIC_FUNCTION_BUNDLE_START owner=analyzeSegmentDifferentiationEffect exports=analyzeSegmentDifferentiationEffect */
const __aivicBundle_1_analyzeSegmentDifferentiationEffect = (() => {
  function analyzeSegmentDifferentiationEffect(input: any): SegmentAnalysisResult {
    // Validate required fields for segment analysis
    if (input.segmentCriteria === undefined && input.segmentId === undefined) {
      throw new Error('セグメント分類基準が定義されていません');
    }
  
    // Handle both standard SegmentAnalysisInput and alternative input shapes
    const segmentId = input.segmentId || '';
    const segmentName = input.segmentName || '';
    const userCount = input.userCount || 0;
    const analysisStartDate = input.analysisStartDate;
    const analysisEndDate = input.analysisEndDate;
    const weeklyMetricsData = input.weeklyMetricsData || [];
    const previousWeeklyMetricsData = input.previousWeeklyMetricsData;
  
    // Calculate averages from weekly metrics
    const calculateAverage = (values: number[]): number => {
      if (values.length === 0) return 0;
      return values.reduce((sum, val) => sum + val, 0) / values.length;
    };
  
    const mealGenerationSuccessRates = weeklyMetricsData.map(
      (m: SegmentMetrics) => m.mealGenerationSuccessRate
    );
    const cookingTimeShorteningDegrees = weeklyMetricsData.map(
      (m: SegmentMetrics) => m.cookingTimeShorteningDegree
    );
    const satisfactionScores = weeklyMetricsData.map(
      (m: SegmentMetrics) => m.satisfactionScore
    );
  
    const averageMealGenerationSuccessRate = calculateAverage(
      mealGenerationSuccessRates
    );
    const averageCookingTimeShorteningDegree = calculateAverage(
      cookingTimeShorteningDegrees
    );
    const averageSatisfactionScore = calculateAverage(satisfactionScores);
  
    // Calculate min/max values
    const mealGenerationSuccessRateMin =
      mealGenerationSuccessRates.length > 0
        ? Math.min(...mealGenerationSuccessRates)
        : 0;
    const mealGenerationSuccessRateMax =
      mealGenerationSuccessRates.length > 0
        ? Math.max(...mealGenerationSuccessRates)
        : 0;
  
    const cookingTimeShorteningDegreeMin =
      cookingTimeShorteningDegrees.length > 0
        ? Math.min(...cookingTimeShorteningDegrees)
        : 0;
    const cookingTimeShorteningDegreeMax =
      cookingTimeShorteningDegrees.length > 0
        ? Math.max(...cookingTimeShorteningDegrees)
        : 0;
  
    const satisfactionScoreMin =
      satisfactionScores.length > 0 ? Math.min(...satisfactionScores) : 0;
    const satisfactionScoreMax =
      satisfactionScores.length > 0 ? Math.max(...satisfactionScores) : 0;
  
    // Format dates as ISO date strings (YYYY-MM-DD)
    const startDateStr = analysisStartDate
      ? analysisStartDate.toISOString().split('T')[0]
      : '';
    const endDateStr = analysisEndDate
      ? analysisEndDate.toISOString().split('T')[0]
      : '';
  
    // Generate CSV export data
    const csvHeader =
      '週,献立生成成功率(%),調理時間短縮度(分),満足度スコア(ポイント)\n';
    const csvRows = weeklyMetricsData
      .map(
        (m: SegmentMetrics) =>
          `${m.week},${m.mealGenerationSuccessRate},${m.cookingTimeShorteningDegree},${m.satisfactionScore}`
      )
      .join('\n');
    const exportData = csvHeader + csvRows;
  
    // Generate graph datasets
    const graphDatasets = [
      {
        label: '献立生成成功率',
        dataPoints: mealGenerationSuccessRates,
      },
      {
        label: '調理時間短縮度',
        dataPoints: cookingTimeShorteningDegrees,
      },
      {
        label: '満足度スコア',
        dataPoints: satisfactionScores,
      },
    ];
  
    // Calculate comparison metrics if previous data is provided
    let comparisonMetrics: { mealGenerationSuccessRateChange: number } | undefined;
    if (previousWeeklyMetricsData && previousWeeklyMetricsData.length > 0) {
      const previousMealRates = previousWeeklyMetricsData.map(
        (m: SegmentMetrics) => m.mealGenerationSuccessRate
      );
      const previousAverageMealRate = calculateAverage(previousMealRates);
      const mealGenerationSuccessRateChange =
        averageMealGenerationSuccessRate - previousAverageMealRate;
  
      comparisonMetrics = {
        mealGenerationSuccessRateChange,
      };
    }
  
    const result: SegmentAnalysisResult = {
      segmentId,
      segmentName,
      userCount,
      averageMealGenerationSuccessRate,
      averageCookingTimeShorteningDegree,
      averageSatisfactionScore,
      mealGenerationSuccessRateMin,
      mealGenerationSuccessRateMax,
      cookingTimeShorteningDegreeMin,
      cookingTimeShorteningDegreeMax,
      satisfactionScoreMin,
      satisfactionScoreMax,
      weeklyTrends: weeklyMetricsData,
      exportFormat: {
        format: 'CSV',
        fileName: `${segmentName}_${startDateStr}_${endDateStr}.csv`,
      },
      exportData,
      unitLabels: {
        mealGenerationSuccessRate: '%',
        cookingTimeShorteningDegree: '分',
        satisfactionScore: 'ポイント',
      },
      analysisStartDate: startDateStr,
      analysisEndDate: endDateStr,
      graphDatasets,
      ...(comparisonMetrics && { comparisonMetrics }),
    };
  
    return result;
  }
  return { analyzeSegmentDifferentiationEffect };
})();
export const analyzeSegmentDifferentiationEffect = __aivicBundle_1_analyzeSegmentDifferentiationEffect.analyzeSegmentDifferentiationEffect;
/* AIVIC_FUNCTION_BUNDLE_END owner=analyzeSegmentDifferentiationEffect */

/* AIVIC_FUNCTION_BUNDLE_START owner=analyzeSegmentStatisticalReliability exports=analyzeSegmentStatisticalReliability */
const __aivicBundle_2_analyzeSegmentStatisticalReliability = (() => {
  function analyzeSegmentStatisticalReliability(
    input: ReliabilityAnalysisInput
  ): ReliabilityAnalysisResult {
    // Validate required input: segmentName
    if (!input.segmentName || String(input.segmentName).trim() === "") {
      throw new Error("segmentName is required");
    }
  
    const sampleSize = input.samples.length;
  
    let reliabilityLevel: string;
    let confidenceScore: number;
    let warningMessage: string;
    let canUseForAnalysis: boolean;
  
    if (sampleSize < 30) {
      reliabilityLevel = "insufficient";
      confidenceScore = 0;
      canUseForAnalysis = false;
  
      if (sampleSize === 1) {
        warningMessage = "サンプルサイズが不足しています";
      } else if (sampleSize === 2) {
        warningMessage = "統計的信頼度が低い";
      } else {
        warningMessage = "サンプルサイズが不足しています";
      }
    } else {
      reliabilityLevel = "sufficient";
      confidenceScore = Math.min(100, 50 + (sampleSize - 30) * 0.5);
      canUseForAnalysis = true;
      warningMessage = "";
    }
  
    return {
      segmentId: input.segmentId,
      sampleSize,
      reliabilityLevel,
      confidenceScore,
      warningMessage,
      canUseForAnalysis,
    };
  }
  return { analyzeSegmentStatisticalReliability };
})();
export const analyzeSegmentStatisticalReliability = __aivicBundle_2_analyzeSegmentStatisticalReliability.analyzeSegmentStatisticalReliability;
/* AIVIC_FUNCTION_BUNDLE_END owner=analyzeSegmentStatisticalReliability */

/* AIVIC_FUNCTION_BUNDLE_START owner=analyzeFeatureUsagePattern exports=analyzeFeatureUsagePattern */
const __aivicBundle_3_analyzeFeatureUsagePattern = (() => {
  function analyzeFeatureUsagePattern(
    input: FeatureUsageAnalysisInput | { usage_logs: FeatureUsageLog[]; analysis_date: string }
  ): FeatureUsageAnalysisResult {
    // Handle empty usage logs
    const usageLogs = "usage_logs" in input ? input.usage_logs : [];
    if (!usageLogs || usageLogs.length === 0) {
      throw new Error("利用ログが空です");
    }
  
    // Extract period information
    const periodStart =
      "period_start" in input ? input.period_start : new Date(input.analysis_date);
    const periodEnd =
      "period_end" in input ? input.period_end : new Date(input.analysis_date);
    
    const competitiveDefinitions =
      "competitive_feature_definitions" in input
        ? input.competitive_feature_definitions
        : [];
  
    // Group logs by feature
    const featureGroups: Record<string, FeatureUsageLog[]> = {};
    for (const log of usageLogs) {
      if (!featureGroups[log.feature_name]) {
        featureGroups[log.feature_name] = [];
      }
      featureGroups[log.feature_name].push(log);
    }
  
    // Calculate feature usage frequency
    const featureUsageFrequency: FeatureUsageFrequencyRecord[] = [];
    const sessionMap: Record<string, Set<string>> = {};
  
    for (const [featureName, logs] of Object.entries(featureGroups)) {
      const accessCount = logs.filter((l) => l.action_type === "access").length;
      const completionCount = logs.filter((l) => l.action_type === "confirm").length;
  
      // Count unique sessions (group by user_id + timestamp proximity)
      if (!sessionMap[featureName]) {
        sessionMap[featureName] = new Set();
      }
      for (const log of logs) {
        sessionMap[featureName].add(log.user_id);
      }
      const totalSessions = sessionMap[featureName].size;
  
      const usageRatePercent =
        totalSessions > 0 ? (completionCount / totalSessions) * 100 : 0;
  
      featureUsageFrequency.push({
        feature_name: featureName,
        access_count: accessCount,
        total_sessions: totalSessions,
        completion_count: completionCount,
        usage_rate_percent: Math.round(usageRatePercent * 100) / 100,
      });
    }
  
    // Calculate feature abandonment analysis
    const featureAbandonmentAnalysis: FeatureAbandonmentRecord[] = [];
  
    for (const [featureName, logs] of Object.entries(featureGroups)) {
      const accessCount = logs.filter((l) => l.action_type === "access").length;
      const completionCount = logs.filter((l) => l.action_type === "confirm").length;
      const abandonmentCount = accessCount - completionCount;
      const abandonmentRatePercent =
        accessCount > 0 ? (abandonmentCount / accessCount) * 100 : 0;
  
      // Build step distribution
      const stepDistribution: Record<string, number> = {};
      for (const log of logs) {
        const stepKey = `step_${log.step_sequence}_${log.action_type}`;
        stepDistribution[stepKey] = (stepDistribution[stepKey] || 0) + 1;
      }
  
      featureAbandonmentAnalysis.push({
        feature_name: featureName,
        abandonment_count: abandonmentCount,
        abandonment_rate_percent: Math.round(abandonmentRatePercent * 100) / 100,
        abandonment_step_distribution: stepDistribution,
      });
    }
  
    // Calculate competitive differentiation
    const proprietaryFeaturesAnalysis: CompetitiveDifferentiationRecord[] = [];
  
    for (const definition of competitiveDefinitions) {
      const featureLogs = featureGroups[definition.feature_name] || [];
      const accessCount = featureLogs.filter(
        (l) => l.action_type === "access"
      ).length;
      const completionCount = featureLogs.filter(
        (l) => l.action_type === "confirm"
      ).length;
      const totalSessions = sessionMap[definition.feature_name]?.size || 0;
  
      const usageFrequencyRank = Object.entries(featureGroups).findIndex(
        ([name]) => name === definition.feature_name
      );
      const userCompletionRatePercent =
        totalSessions > 0 ? (completionCount / totalSessions) * 100 : 0;
  
      const satisfactionIndicator =
        userCompletionRatePercent >= 80
          ? "high"
          : userCompletionRatePercent >= 50
            ? "medium"
            : "low";
  
      proprietaryFeaturesAnalysis.push({
        feature_name: definition.feature_name,
        is_proprietary: definition.is_proprietary,
        competitive_advantage_score: definition.competitive_advantage_score,
        usage_frequency_rank: usageFrequencyRank + 1,
        user_completion_rate_percent: Math.round(userCompletionRatePercent * 100) / 100,
        satisfaction_indicator: satisfactionIndicator,
      });
    }
  
    // Build analysis metadata
    const uniqueFeatures = Object.keys(featureGroups).length;
    const totalLogsProcessed = usageLogs.length;
    const totalSessionsAnalyzed = Object.values(sessionMap).reduce(
      (sum, sessions) => sum + sessions.size,
      0
    );
  
    // Build exportable report data
    const reportGeneratedTimestamp = new Date().toISOString();
    const usageFrequencyTable = featureUsageFrequency.map((record) => ({
      feature_name: record.feature_name,
      access_count: record.access_count,
      total_sessions: record.total_sessions,
      completion_count: record.completion_count,
      usage_rate_percent: record.usage_rate_percent,
    }));
  
    const abandonmentAnalysisTable = featureAbandonmentAnalysis.map((record) => ({
      feature_name: record.feature_name,
      abandonment_count: record.abandonment_count,
      abandonment_rate_percent: record.abandonment_rate_percent,
      abandonment_step_distribution: record.abandonment_step_distribution,
    }));
  
    const competitiveAnalysisTable = proprietaryFeaturesAnalysis.map((record) => ({
      feature_name: record.feature_name,
      is_proprietary: record.is_proprietary,
      competitive_advantage_score: record.competitive_advantage_score,
      usage_frequency_rank: record.usage_frequency_rank,
      user_completion_rate_percent: record.user_completion_rate_percent,
      satisfaction_indicator: record.satisfaction_indicator,
    }));
  
    return {
      feature_usage_frequency: featureUsageFrequency,
      feature_abandonment_analysis: featureAbandonmentAnalysis,
      competitive_differentiation_basis: {
        proprietary_features_analysis: proprietaryFeaturesAnalysis,
      },
      analysis_metadata: {
        analysis_period_start: periodStart,
        analysis_period_end: periodEnd,
        total_logs_processed: totalLogsProcessed,
        total_sessions_analyzed: totalSessionsAnalyzed,
        unique_features_tracked: uniqueFeatures,
      },
      exportable_report_data: {
        report_generated_timestamp: reportGeneratedTimestamp,
        usage_frequency_table: usageFrequencyTable,
        abandonment_analysis_table: abandonmentAnalysisTable,
        competitive_analysis_table: competitiveAnalysisTable,
      },
      filterable_dimensions: ["feature_name", "time_period", "user_segment"],
    };
  }
  return { analyzeFeatureUsagePattern };
})();
export const analyzeFeatureUsagePattern = __aivicBundle_3_analyzeFeatureUsagePattern.analyzeFeatureUsagePattern;
/* AIVIC_FUNCTION_BUNDLE_END owner=analyzeFeatureUsagePattern */

/* AIVIC_FUNCTION_BUNDLE_START owner=analyzeFeatureUsagePatterns exports=analyzeFeatureUsagePatterns */
const __aivicBundle_4_analyzeFeatureUsagePatterns = (() => {
  function analyzeFeatureUsagePatterns(input: {
    analysisId: string;
    analysisPeriod: { startDate: Date; endDate: Date };
    featureUsageRecords: Array<{
      userId: string;
      featureName: string;
      accessCount: number;
      abandonmentPoint: string;
      abandonmentTimestamp: Date;
    }>;
    totalUsersAnalyzed: number;
    completionCount: number;
    abandonmentCount: number;
  }): {
    alertLevel: string;
    alertMessage: string;
    abandonmentRate: number;
    detailedLog: string;
    abandonmentPointDistribution: Record<string, number>;
    analysisId: string;
    totalUsersAnalyzed: number;
    completionCount: number;
    abandonmentCount: number;
    hasError: boolean;
    errorDetails?: string;
  } {
    const {
      analysisId,
      analysisPeriod,
      featureUsageRecords,
      totalUsersAnalyzed,
      completionCount,
      abandonmentCount,
    } = input;
  
    // Validate analysisPeriod is provided and has valid structure
    if (
      !analysisPeriod ||
      !analysisPeriod.startDate ||
      !analysisPeriod.endDate
    ) {
      return {
        alertLevel: 'error',
        alertMessage: '分析期間が不正です',
        abandonmentRate: 0,
        detailedLog: 'error: 分析期間が指定されていません',
        abandonmentPointDistribution: {},
        analysisId,
        totalUsersAnalyzed,
        completionCount,
        abandonmentCount,
        hasError: true,
        errorDetails: 'analysisPeriod is required and must have startDate and endDate',
      };
    }
  
    // Verify period order
    const startTime = new Date(analysisPeriod.startDate).getTime();
    const endTime = new Date(analysisPeriod.endDate).getTime();
    if (startTime > endTime) {
      return {
        alertLevel: 'error',
        alertMessage: '分析期間の開始日が終了日より後です',
        abandonmentRate: 0,
        detailedLog: 'error: 分析期間が不正です',
        abandonmentPointDistribution: {},
        analysisId,
        totalUsersAnalyzed,
        completionCount,
        abandonmentCount,
        hasError: true,
        errorDetails: 'startDate must be before or equal to endDate',
      };
    }
  
    const abandonmentRate =
      totalUsersAnalyzed > 0
        ? Math.round((abandonmentCount / totalUsersAnalyzed) * 100)
        : 0;
  
    const abandonmentPointDistribution: Record<string, number> = {};
    for (const record of featureUsageRecords) {
      const point = record.abandonmentPoint;
      abandonmentPointDistribution[point] =
        (abandonmentPointDistribution[point] || 0) + 1;
    }
  
    let alertLevel = 'normal';
    let alertMessage = '離脱なし';
    let detailedLog = 'normal: 離脱率 0%';
  
    if (abandonmentRate === 100 && abandonmentCount > 0) {
      alertLevel = 'critical';
      alertMessage = `ユーザー離脱が100%です`;
      detailedLog = `critical: 離脱率 100%`;
    } else if (abandonmentRate > 50) {
      alertLevel = 'warning';
      alertMessage = `ユーザー離脱が${abandonmentRate}%です`;
      detailedLog = `warning: 離脱率 ${abandonmentRate}%`;
    } else if (abandonmentRate > 0) {
      alertLevel = 'info';
      alertMessage = `ユーザー離脱が${abandonmentRate}%です`;
      detailedLog = `info: 離脱率 ${abandonmentRate}%`;
    } else {
      alertLevel = 'normal';
      alertMessage = '離脱なし';
      detailedLog = 'normal: 離脱率 0%';
    }
  
    return {
      alertLevel,
      alertMessage,
      abandonmentRate,
      detailedLog,
      abandonmentPointDistribution,
      analysisId,
      totalUsersAnalyzed,
      completionCount,
      abandonmentCount,
      hasError: false,
    };
  }
  return { analyzeFeatureUsagePatterns };
})();
export const analyzeFeatureUsagePatterns = __aivicBundle_4_analyzeFeatureUsagePatterns.analyzeFeatureUsagePatterns;
/* AIVIC_FUNCTION_BUNDLE_END owner=analyzeFeatureUsagePatterns */

/* AIVIC_FUNCTION_BUNDLE_START owner=classifyPainFactors exports=classifyPainFactors */
const __aivicBundle_5_classifyPainFactors = (() => {
  function classifyPainFactors(
    input: PainFactorClassificationInput,
  ): PainFactorClassificationResult {
    const {
      exit_point,
      constraint_pattern,
      user_id,
      family_id,
      timestamp,
      input_value,
      field_name,
    } = input;
  
    // Determine pain_factor_category and priority based on constraint_pattern
    let pain_factor_category: string;
    let priority: number;
  
    if (constraint_pattern === 'mandatory_field_missing') {
      pain_factor_category = 'input_incomplete';
      priority = 1;
    } else if (constraint_pattern === 'invalid_data_type') {
      pain_factor_category = 'data_validation_error';
      priority = 2;
    } else if (constraint_pattern === 'limit_exceeded') {
      pain_factor_category = 'budget_constraint_violation';
      priority = 3;
    } else if (constraint_pattern === 'multiple_constraint_conflict') {
      pain_factor_category = 'conflicting_constraints';
      priority = 2;
    } else {
      pain_factor_category = 'system_error';
      priority = 2;
    }
  
    // Use all required inputs in validation to ensure they are connected to business logic
    if (!user_id || String(user_id).trim() === '') {
      throw new Error('user_id is required');
    }
    if (!family_id || String(family_id).trim() === '') {
      throw new Error('family_id is required');
    }
    if (!timestamp) {
      throw new Error('timestamp is required');
    }
    if (input_value === undefined) {
      throw new Error('input_value is required');
    }
    if (!field_name || String(field_name).trim() === '') {
      throw new Error('field_name is required');
    }
  
    return {
      exit_point,
      constraint_pattern,
      pain_factor_category,
      priority,
      classification_timestamp: new Date(),
    };
  }
  return { classifyPainFactors };
})();
export const classifyPainFactors = __aivicBundle_5_classifyPainFactors.classifyPainFactors;
/* AIVIC_FUNCTION_BUNDLE_END owner=classifyPainFactors */

/* AIVIC_FUNCTION_BUNDLE_START owner=analyzeMenuGenerationFlowForPainFactors exports=analyzeMenuGenerationFlowForPainFactors */
const __aivicBundle_6_analyzeMenuGenerationFlowForPainFactors = (() => {
  function analyzeMenuGenerationFlowForPainFactors(
    input: MenuGenerationFlowAnalysisInput
  ): any {
    const { user_id, menu_generation_flow_history } = input;
  
    if (!menu_generation_flow_history || menu_generation_flow_history.length === 0) {
      throw new Error('献立履歴が見つかりません');
    }
  
    const painFactors: Array<{
      flowId: string;
      exitPoint: string;
      constraintPattern: string;
      painFactorCategory: string;
      priority: number;
    }> = [];
  
    for (const flow of menu_generation_flow_history) {
      const exitPoint = flow.exitPoint || 'unknown';
      const constraintPattern = flow.constraintPattern || 'unspecified';
  
      let painFactorCategory = 'other';
      let priority = 3;
  
      if (
        exitPoint.includes('budget') ||
        constraintPattern.includes('budget')
      ) {
        painFactorCategory = 'budget_constraint';
        priority = 1;
      } else if (
        exitPoint.includes('time') ||
        constraintPattern.includes('time')
      ) {
        painFactorCategory = 'time_constraint';
        priority = 2;
      } else if (
        exitPoint.includes('ingredient') ||
        constraintPattern.includes('ingredient')
      ) {
        painFactorCategory = 'ingredient_availability';
        priority = 2;
      } else if (
        exitPoint.includes('preference') ||
        constraintPattern.includes('preference')
      ) {
        painFactorCategory = 'preference_mismatch';
        priority = 3;
      }
  
      painFactors.push({
        flowId: flow.flowId || `flow_${painFactors.length}`,
        exitPoint,
        constraintPattern,
        painFactorCategory,
        priority,
      });
    }
  
    return {
      user_id,
      painFactors,
      totalFlowsAnalyzed: menu_generation_flow_history.length,
      analysisTimestamp: new Date().toISOString(),
    };
  }
  return { analyzeMenuGenerationFlowForPainFactors };
})();
export const analyzeMenuGenerationFlowForPainFactors = __aivicBundle_6_analyzeMenuGenerationFlowForPainFactors.analyzeMenuGenerationFlowForPainFactors;
/* AIVIC_FUNCTION_BUNDLE_END owner=analyzeMenuGenerationFlowForPainFactors */

/* AIVIC_FUNCTION_BUNDLE_START owner=generatePainMatrixByPriority exports=generatePainMatrixByPriority */
const __aivicBundle_7_generatePainMatrixByPriority = (() => {
  function generatePainMatrixByPriority(
    reasons: WithdrawalReason[]
  ): PainMatrixResult {
    const matrixId = randomUUID();
    const generatedAt = new Date().toISOString();
  
    if (!reasons || reasons.length === 0) {
      return {
        matrix_id: matrixId,
        total_rows: 0,
        total_columns: 0,
        cells: [],
        generated_at: generatedAt,
      };
    }
  
    // Group reasons by priority_level and importance_score
    const groupedByPriority = new Map<
      string,
      WithdrawalReason[]
    >();
  
    reasons.forEach((reason) => {
      const key = `${reason.priority_level}_${reason.importance_score}`;
      if (!groupedByPriority.has(key)) {
        groupedByPriority.set(key, []);
      }
      groupedByPriority.get(key)!.push(reason);
    });
  
    // Sort each group by registration_order
    groupedByPriority.forEach((group) => {
      group.sort((a, b) => a.registration_order - b.registration_order);
    });
  
    // Build cells: each row is a priority group, each column is a reason in that group
    const cells: PainMatrixCell[] = [];
    let rowIndex = 0;
  
    // Sort priority groups for consistent row ordering
    const sortedKeys = Array.from(groupedByPriority.keys()).sort();
  
    sortedKeys.forEach((key) => {
      const group = groupedByPriority.get(key)!;
      const [priorityLevel, importanceScore] = key.split("_").map(Number);
  
      group.forEach((reason, columnIndex) => {
        const cellId = randomUUID();
        cells.push({
          cell_id: cellId,
          priority_level: priorityLevel,
          importance_score: importanceScore,
          withdrawal_reason_id: reason.withdrawal_reason_id,
          reason_text: reason.reason_text,
          row_index: rowIndex,
          column_index: columnIndex,
          sort_order: columnIndex + 1,
        });
      });
  
      rowIndex++;
    });
  
    const totalRows = groupedByPriority.size;
    const totalColumns = Math.max(
      ...Array.from(groupedByPriority.values()).map((g) => g.length)
    );
  
    return {
      matrix_id: matrixId,
      total_rows: totalRows,
      total_columns: totalColumns,
      cells,
      generated_at: generatedAt,
    };
  }
  return { generatePainMatrixByPriority };
})();
export const generatePainMatrixByPriority = __aivicBundle_7_generatePainMatrixByPriority.generatePainMatrixByPriority;
/* AIVIC_FUNCTION_BUNDLE_END owner=generatePainMatrixByPriority */

/* AIVIC_FUNCTION_BUNDLE_START owner=analyzeNutrientIntake exports=analyzeNutrientIntake */
const __aivicBundle_8_analyzeNutrientIntake = (() => {
  function analyzeNutrientIntake(
    input: NutritionIntakeAnalysisInput
  ): NutritionIntakeAnalysisResult {
    const nutritionStandardsMap: Record<string, NutritionStandard> = {
      female_20_49: {
        calories: 2000,
        protein: 50,
        fat: 56,
        carbohydrates: 275,
        vitamin_a: 700,
        calcium: 650,
      },
      female_50_69: {
        calories: 1700,
        protein: 50,
        fat: 47,
        carbohydrates: 234,
        vitamin_a: 700,
        calcium: 650,
      },
      female_70_plus: {
        calories: 1600,
        protein: 50,
        fat: 44,
        carbohydrates: 220,
        vitamin_a: 700,
        calcium: 650,
      },
      male_6_7: {
        calories: 1450,
        protein: 30,
        fat: 41,
        carbohydrates: 200,
        vitamin_a: 500,
        calcium: 650,
      },
      male_8_9: {
        calories: 1600,
        protein: 35,
        fat: 45,
        carbohydrates: 220,
        vitamin_a: 600,
        calcium: 650,
      },
      male_10_11: {
        calories: 1950,
        protein: 40,
        fat: 55,
        carbohydrates: 268,
        vitamin_a: 700,
        calcium: 700,
      },
      male_20_49: {
        calories: 2500,
        protein: 60,
        fat: 70,
        carbohydrates: 344,
        vitamin_a: 900,
        calcium: 800,
      },
      male_50_69: {
        calories: 2100,
        protein: 60,
        fat: 59,
        carbohydrates: 288,
        vitamin_a: 900,
        calcium: 750,
      },
      male_70_plus: {
        calories: 1850,
        protein: 60,
        fat: 52,
        carbohydrates: 254,
        vitamin_a: 900,
        calcium: 700,
      },
    };
  
    function getAgeGroupKey(age: number, gender: string): string {
      const genderLower = gender.toLowerCase();
      if (genderLower === "female") {
        if (age >= 20 && age <= 49) return "female_20_49";
        if (age >= 50 && age <= 69) return "female_50_69";
        return "female_70_plus";
      } else {
        if (age >= 6 && age <= 7) return "male_6_7";
        if (age >= 8 && age <= 9) return "male_8_9";
        if (age >= 10 && age <= 11) return "male_10_11";
        if (age >= 20 && age <= 49) return "male_20_49";
        if (age >= 50 && age <= 69) return "male_50_69";
        return "male_70_plus";
      }
    }
  
    const nutrition_standards: Record<string, NutritionStandard> = {};
    const actual_intake: Record<string, NutritionStandard> = {};
    const achievement_rates: Record<string, Record<string, number>> = {};
    const compliance: Record<string, Record<string, ComplianceStatus>> = {};
  
    for (const member of input.family_members) {
      const ageGroupKey = getAgeGroupKey(member.age, member.gender);
      nutrition_standards[member.member_id] =
        nutritionStandardsMap[ageGroupKey];
  
      actual_intake[member.member_id] = {
        calories: 0,
        protein: 0,
        fat: 0,
        carbohydrates: 0,
        vitamin_a: 0,
        calcium: 0,
      };
    }
  
    for (const record of input.meal_records) {
      if (actual_intake[record.member_id]) {
        actual_intake[record.member_id].calories += record.calories;
        actual_intake[record.member_id].protein += record.protein;
        actual_intake[record.member_id].fat += record.fat;
        actual_intake[record.member_id].carbohydrates +=
          record.carbohydrates;
        actual_intake[record.member_id].vitamin_a += record.vitamin_a;
        actual_intake[record.member_id].calcium += record.calcium;
      }
    }
  
    for (const member of input.family_members) {
      const memberId = member.member_id;
      const standard = nutrition_standards[memberId];
      const actual = actual_intake[memberId];
  
      achievement_rates[memberId] = {};
      compliance[memberId] = {};
  
      const nutrients: Array<keyof NutritionStandard> = [
        "calories",
        "protein",
        "fat",
        "carbohydrates",
        "vitamin_a",
        "calcium",
      ];
  
      for (const nutrient of nutrients) {
        const standardValue = standard[nutrient];
        const actualValue = actual[nutrient];
  
        const rate =
          standardValue > 0
            ? Math.round((actualValue / standardValue) * 100)
            : 0;
        achievement_rates[memberId][nutrient] = rate;
  
        let status: string;
        if (rate < 90) {
          status = "under";
        } else if (rate > 110) {
          status = "over";
        } else {
          status = "appropriate";
        }
  
        const isCompliant = rate >= 90 && rate <= 110;
  
        compliance[memberId][nutrient] = {
          status,
          percentage: rate,
          is_compliant: isCompliant,
        };
      }
    }
  
    const analysisDate = new Date(input.analysis_date);
    const analysis_timestamp = analysisDate.toISOString();
  
    return {
      nutrition_standards,
      actual_intake,
      achievement_rates,
      compliance,
      analysis_timestamp,
    };
  }
  return { analyzeNutrientIntake };
})();
export const analyzeNutrientIntake = __aivicBundle_8_analyzeNutrientIntake.analyzeNutrientIntake;
/* AIVIC_FUNCTION_BUNDLE_END owner=analyzeNutrientIntake */

/* AIVIC_FUNCTION_BUNDLE_START owner=analyzeNutritionAchievementRate exports=analyzeNutritionAchievementRate */
const __aivicBundle_9_analyzeNutritionAchievementRate = (() => {
  function analyzeNutritionAchievementRate(
    input: NutritionAchievementRateInput
  ): NutritionAchievementRateResult {
    // Validate user_id
    if (!input.user_id || input.user_id.trim() === '') {
      throw new Error('ユーザーIDが指定されていません');
    }
  
    // Validate target_date
    if (!input.target_date || isNaN(input.target_date.getTime())) {
      throw new Error('日付が無効です');
    }
  
    // Validate nutrition_standards
    if (!input.nutrition_standards || input.nutrition_standards.length === 0) {
      return {
        has_nutrition_logs: input.nutrition_logs && input.nutrition_logs.length > 0,
        achievement_rates: [],
        is_dashboard_renderable: false,
        error_message: '栄養基準値が設定されていません',
      };
    }
  
    const hasLogs = input.nutrition_logs && input.nutrition_logs.length > 0;
  
    // Create a map of nutrient logs by nutrient_name for quick lookup
    const logsMap = new Map<string, number>();
    if (hasLogs) {
      for (const log of input.nutrition_logs) {
        logsMap.set(log.nutrient_name, log.intake_amount);
      }
    }
  
    // Calculate achievement rates for each standard
    const achievementRates = input.nutrition_standards.map((standard) => {
      let achievementRate = 0;
  
      if (hasLogs && logsMap.has(standard.nutrient_name)) {
        const intakeAmount = logsMap.get(standard.nutrient_name)!;
        achievementRate = Math.round(
          (intakeAmount / standard.daily_target) * 100
        );
      }
  
      return {
        nutrient_name: standard.nutrient_name,
        achievement_rate: achievementRate,
      };
    });
  
    return {
      has_nutrition_logs: hasLogs,
      achievement_rates: achievementRates,
      is_dashboard_renderable: true,
      error_message: '',
    };
  }
  return { analyzeNutritionAchievementRate };
})();
export const analyzeNutritionAchievementRate = __aivicBundle_9_analyzeNutritionAchievementRate.analyzeNutritionAchievementRate;
/* AIVIC_FUNCTION_BUNDLE_END owner=analyzeNutritionAchievementRate */

/* AIVIC_FUNCTION_BUNDLE_START owner=calculateNutritionAchievementByAgeGroup exports=calculateNutritionAchievementByAgeGroup */
const __aivicBundle_10_calculateNutritionAchievementByAgeGroup = (() => {
  function getAgeGroupNutritionStandard(age: number): { calories: number; protein: number } {
    if (age < 1) {
      return { calories: 1000, protein: 15 };
    } else if (age < 3) {
      return { calories: 1100, protein: 18 };
    } else if (age < 6) {
      return { calories: 1200, protein: 20 };
    } else if (age < 9) {
      return { calories: 1800, protein: 30 };
    } else if (age < 12) {
      return { calories: 2000, protein: 35 };
    } else if (age < 15) {
      return { calories: 2200, protein: 40 };
    } else if (age < 18) {
      return { calories: 2400, protein: 45 };
    } else if (age < 50) {
      return { calories: 2100, protein: 50 };
    } else if (age < 65) {
      return { calories: 2000, protein: 50 };
    } else {
      return { calories: 1850, protein: 50 };
    }
  }
  
   function calculateNutritionAchievementByAgeGroup(
    family_members: FamilyMember[],
    nutrition_intake_data: Array<{ member_id: string; date: string; calories: number; protein: number }>
  ): AgeGroupNutritionInput[] {
    const results: AgeGroupNutritionInput[] = [];
  
    for (const member of family_members) {
      if (member.age < 0) {
        throw new Error(`無効な年齢: メンバー ${member.member_id} の年齢が負数です`);
      }
  
      const intakeRecord = nutrition_intake_data.find(
        (record) => record.member_id === member.member_id
      );
  
      if (!intakeRecord) {
        throw new Error(`メンバー ${member.member_id} に対応する栄養摂取データが見つかりません`);
      }
  
      const standard = getAgeGroupNutritionStandard(member.age);
  
      const caloriesAchievementScore =
        standard.calories > 0 ? (intakeRecord.calories / standard.calories) * 100 : 0;
      const proteinAchievementScore =
        standard.protein > 0 ? (intakeRecord.protein / standard.protein) * 100 : 0;
  
      results.push({
        member_id: member.member_id,
        age: member.age,
        nutrition_standard: {
          calories: standard.calories,
          protein: standard.protein,
        },
        nutrition_actual: {
          calories: intakeRecord.calories,
          protein: intakeRecord.protein,
        },
        achievement_score: {
          calories: caloriesAchievementScore,
          protein: proteinAchievementScore,
        },
      });
    }
  
    return results;
  }
  return { calculateNutritionAchievementByAgeGroup };
})();
export const calculateNutritionAchievementByAgeGroup = __aivicBundle_10_calculateNutritionAchievementByAgeGroup.calculateNutritionAchievementByAgeGroup;
/* AIVIC_FUNCTION_BUNDLE_END owner=calculateNutritionAchievementByAgeGroup */
